<?php
$content_detail = $this->arrContent;
$category_detail = $this->arrCategoryDetail;
?>
<div class="td-crumb-container">
    <div class="entry-crumbs">
        <span>
            <a title="Home" class="entry-crumb" itemprop="url"  href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <span itemprop="title"><i class="fa fa-home"></i> Home</span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep"></i>
        <span>
            <a title="<?php echo $category_detail['cate_name'] ?>" class="entry-crumb" itemprop="url" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' =>  $category_detail['cate_slug'], 'cateId' => $category_detail['cate_id']]) ?>">
                <span itemprop="title"><?php echo $category_detail['cate_name'] ?></span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep"></i>
        <span class=td-bred-no-url-last>
            <meta itemprop=title content="<?php echo $content_detail['cont_title']; ?>">
            <meta itemprop=url content="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' =>  $content_detail['cont_slug'], 'contentId' => $content_detail['cont_id']]) ?>">
            <?php echo $content_detail['cont_title']; ?>
        </span>
    </div>
</div>
<div class="td-ss-main-content">
    <article id=post-95
             class="post-95 post type-post status-publish format-standard has-post-thumbnail hentry category-tagdiv-gadgets"
             itemscope itemtype="http://schema.org/Article">

        <div class=td-post-header>
            <header class=td-post-title>
                <h1 class=entry-title><?php echo $content_detail['cont_title'] ?></h1>
                <div class=td-module-meta-info>
                <span class=td-post-date>
                    <time class="entry-date updated td-module-date"
                          datetime="<?php echo date("d-m-Y", $content_detail['created_date']); ?>"><?php echo date("d-m-Y", $content_detail['created_date']); ?></time></span>
                    <div class=td-post-views>
                        <i class=td-icon-views></i>
                        <span class=td-nr-views-95><?php echo $content_detail['cont_views'] ?></span>
                    </div>
                </div>
            </header>
        </div>

        <div class="td-post-sharing td-post-sharing-top ">
            <div class=td-default-sharing>
                <a class="td-social-sharing-buttons td-social-facebook"
                   href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-facebook></i>
                    <div class=td-social-but-text>Share on Facebook</div>
                </a>
                <a class="td-social-sharing-buttons td-social-twitter"
                   href="https://twitter.com/intent/tweet?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front&amp;url=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F&amp;via=Newspaper+7"><i
                        class=td-icon-twitter></i>
                    <div class=td-social-but-text>Tweet on Twitter</div>
                </a>
                <a class="td-social-sharing-buttons td-social-google"
                   href="http://plus.google.com/share?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-googleplus></i></a>
                <a class="td-social-sharing-buttons td-social-pinterest"
                   href="http://pinterest.com/pin/create/button/?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/&amp;media=http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/36.jpg&amp;description=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-pinterest></i></a>
                <a class="td-social-sharing-buttons td-social-whatsapp"
                   href="whatsapp://send?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front%20-%20http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"><i
                        class=td-icon-whatsapp></i></a>
            </div>
        </div>

        <div class=td-post-content>
            <h3 class="entry-title"><?php echo $content_detail['cont_description'] ?></h3>
            <?php echo $content_detail['cont_detail'] ?>
        </div>
        <footer>
            <div class=td-post-source-tags>
            </div>
            <div class="td-post-sharing td-post-sharing-bottom td-with-like"><span
                    class=td-post-share-title>SHARE</span>
                <div class=td-default-sharing>
                    <a class="td-social-sharing-buttons td-social-facebook"
                       href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"
                       onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                            class=td-icon-facebook></i>
                        <div class=td-social-but-text>Facebook</div>
                    </a>
                    <a class="td-social-sharing-buttons td-social-twitter"
                       href="https://twitter.com/intent/tweet?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front&amp;url=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F&amp;via=Newspaper+7"><i
                            class=td-icon-twitter></i>
                        <div class=td-social-but-text>Twitter</div>
                    </a>
                    <a class="td-social-sharing-buttons td-social-google"
                       href="http://plus.google.com/share?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/"
                       onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                            class=td-icon-googleplus></i></a>
                    <a class="td-social-sharing-buttons td-social-pinterest"
                       href="http://pinterest.com/pin/create/button/?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/&amp;media=http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/36.jpg&amp;description=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front"
                       onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                            class=td-icon-pinterest></i></a>
                    <a class="td-social-sharing-buttons td-social-whatsapp"
                       href="whatsapp://send?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front%20-%20http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"><i
                            class=td-icon-whatsapp></i></a>
                </div>
                <div class=td-classic-sharing>
                    <ul>
                        <li class=td-classic-facebook>
                            <iframe frameBorder=0
                                    src="http://www.facebook.com/plugins/like.php?href=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/&amp;layout=button_count&amp;show_faces=false&amp;width=105&amp;action=like&amp;colorscheme=light&amp;height=21"
                                    style="border:none;overflow:hidden;width:105px;height:21px;background-color:transparent"></iframe>
                        </li>
                        <li class=td-classic-twitter><a href="https://twitter.com/share" class=twitter-share-button
                                                        data-url="http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/"
                                                        data-text="HTC launches another selfie-phone with an UltraPixel camera up front"
                                                        data-via="" data-lang=en>tweet</a>
                            <script>!function (d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (!d.getElementById(id)) {
                                        js = d.createElement(s);
                                        js.id = id;
                                        js.src = "http://platform.twitter.com/widgets.js";
                                        fjs.parentNode.insertBefore(js, fjs);
                                    }
                                }(document, "script", "twitter-wjs");</script>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="td-block-row td-post-next-prev">
                <div class="td-block-span6 td-post-prev-post">
                    <div class=td-post-next-prev-content><span>Previous article</span><a
                            href="http://demo.tagdiv.com/newspaper/td-post-ferrari-the-latest-1035bhp-monster-is-too-powerful-for-the-road/">Ferrari
                            the latest 1035bhp monster is too powerful for the road</a></div>
                </div>
                <div class=td-next-prev-separator></div>
                <div class="td-block-span6 td-post-next-post">
                    <div class=td-post-next-prev-content><span>Next article</span><a
                            href="http://demo.tagdiv.com/newspaper/td-post-more-reasons-to-choose-the-htc-one-m9-instead-of-the-samsung-galaxy-s6-edge/">More
                            reasons to choose the HTC One M9 instead of the Samsung Galaxy S6 Edge</a></div>
                </div>
            </div>
            <div class=author-box-wrap><a href="http://demo.tagdiv.com/newspaper/author/marius2/"><img
                        src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/avatar2.jpg" width=96 height=96
                        alt="Matt Cloey" class="avatar avatar-96 wp-user-avatar wp-user-avatar-96 alignnone photo"/></a>
                <div class=desc>
                    <div class="td-author-name vcard author"><span class=fn><a
                                href="http://demo.tagdiv.com/newspaper/author/marius2/">Matt Cloey</a></span></div>
                    <div class=td-author-url><a href="http://www.matt-cloey.com/">http://www.matt-cloey.com</a></div>
                    <div class=td-author-description>Lorem ipsum dolor sit amet consectetur adipiscing elit. Vestibulum
                        ac
                        vehicula leo. Donec urna lacus gravida ac vulputate sagittis tristique vitae lectus. Nullam
                        rhoncus
                        tortor at dignissim vehicula.
                    </div>
                    <div class=td-author-social>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Behance>
<i class="td-icon-font td-icon-behance"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Evernote>
<i class="td-icon-font td-icon-evernote"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Facebook>
<i class="td-icon-font td-icon-facebook"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Reddit>
<i class="td-icon-font td-icon-reddit"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Vimeo>
<i class="td-icon-font td-icon-vimeo"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=VKontakte>
<i class="td-icon-font td-icon-vk"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Youtube>
<i class="td-icon-font td-icon-youtube"></i>
</a>
</span></div>
                    <div class=clearfix></div>
                </div>
            </div>
        <span style=display:none itemprop=author itemscope itemtype="https://schema.org/Person"><meta itemprop=name
                                                                                                      content="Matt Cloey"></span>
            <meta itemprop=datePublished content="2015-04-22T05:23:26+00:00">
            <meta itemprop=dateModified content="2015-04-28T10:50:04+00:00">
            <meta itemscope itemprop=mainEntityOfPage itemType="https://schema.org/WebPage"
                  itemid="http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/"/>
        <span style=display:none itemprop=publisher itemscope itemtype="https://schema.org/Organization"><span
                style=display:none itemprop=logo itemscope itemtype="https://schema.org/ImageObject"><meta itemprop=url
                                                                                                           content="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/logo-header.png"></span><meta
                itemprop=name content="Newspaper 7"></span>
            <meta itemprop="headline " content="HTC launches another selfie-phone with an UltraPixel camera up front">
        <span style=display:none itemprop=image itemscope itemtype="https://schema.org/ImageObject"><meta itemprop=url
                                                                                                          content="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/36.jpg"><meta
                itemprop=width content=1687><meta itemprop=height content=1126></span></footer>
    </article>
</div>