<?php
$content_detail = $this->arrContent;
$category_detail = $this->arrCategoryDetail;
$arrKeywordList = $this->arrKeywordList;
$list_category = unserialize(ARR_CATEGORY);
?>
<div class="td-crumb-container">
    <div class="entry-crumbs">
        <span>
            <a title="Home" class="entry-crumb" itemprop="url"
               href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <span itemprop="title"><i class="fa fa-home"></i> Home</span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep"></i>
        <span>
            <a title="<?php echo $category_detail['cate_name'] ?>" class="entry-crumb" itemprop="url"
               href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $category_detail['cate_slug'], 'cateId' => $category_detail['cate_id']]) ?>">
                <span itemprop="title"><?php echo $category_detail['cate_name'] ?></span>
            </a>
        </span>
        <i class="td-icon-right td-bread-sep"></i>
        <span class=td-bred-no-url-last>
            <meta itemprop=title content="<?php echo $content_detail['cont_title']; ?>">
            <meta itemprop=url
                  content="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content_detail['cont_slug'], 'contentId' => $content_detail['cont_id']]) ?>">
            <?php echo $content_detail['cont_title']; ?>
        </span>
    </div>
</div>
<div class="td-ss-main-content">
    <article id=post-95
             class="post-95 post type-post status-publish format-standard has-post-thumbnail hentry category-tagdiv-gadgets"
             itemscope itemtype="http://schema.org/Article">

        <div class=td-post-header>
            <header class=td-post-title>
                <h1 class=entry-title><?php echo $content_detail['cont_title'] ?></h1>
                <div class=td-module-meta-info>
                <span class=td-post-date>
                    <time class="entry-date updated td-module-date"
                          datetime="<?php echo date("d-m-Y", $content_detail['created_date']); ?>"><?php echo date("d-m-Y", $content_detail['created_date']); ?></time></span>
                    <div class=td-post-views>
                        <i class=td-icon-views></i>
                        <span class=td-nr-views-95><?php echo $content_detail['cont_views'] ?></span>
                    </div>
                </div>
            </header>
        </div>

        <div class="td-post-sharing td-post-sharing-top ">
            <div class=td-default-sharing>
                <a class="td-social-sharing-buttons td-social-facebook"
                   href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-facebook></i>
                    <div class=td-social-but-text>Share on Facebook</div>
                </a>
                <a class="td-social-sharing-buttons td-social-twitter"
                   href="https://twitter.com/intent/tweet?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front&amp;url=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F&amp;via=Newspaper+7"><i
                        class=td-icon-twitter></i>
                    <div class=td-social-but-text>Tweet on Twitter</div>
                </a>
                <a class="td-social-sharing-buttons td-social-google"
                   href="http://plus.google.com/share?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-googleplus></i></a>
                <a class="td-social-sharing-buttons td-social-pinterest"
                   href="http://pinterest.com/pin/create/button/?url=http://demo.tagdiv.com/newspaper/td-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front/&amp;media=http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/36.jpg&amp;description=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front"
                   onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                        class=td-icon-pinterest></i></a>
                <a class="td-social-sharing-buttons td-social-whatsapp"
                   href="whatsapp://send?text=HTC+launches+another+selfie-phone+with+an+UltraPixel+camera+up+front%20-%20http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2Ftd-post-htc-launches-another-selfie-phone-with-an-ultrapixel-camera-up-front%2F"><i
                        class=td-icon-whatsapp></i></a>
            </div>
        </div>

        <div class=td-post-content>
            <h3 class="entry-title"><?php echo $content_detail['cont_description'] ?></h3>
            <?php echo $content_detail['cont_detail'] ?>
        </div>
        <footer>
            <?php if (!empty($arrKeywordList)) { ?>
                <div class="td-post-source-tags">
                    <ul class="td-tags td-post-small-box clearfix">
                        <li><span>KEYWORD</span></li>
                        <?php foreach ($arrKeywordList as $keyword) { ?>
                            <li>
                                <a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'],'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
            <div class="td-post-sharing td-post-sharing-bottom td-with-like">
                <span class=td-post-share-title>SHARE</span>
                <div class=td-default-sharing>
                    <a class="td-social-sharing-buttons td-social-facebook"
                       href="http://www.facebook.com/sharer.php?u=<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                       onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                            class=td-icon-facebook></i>
                        <div class=td-social-but-text>Facebook</div>
                    </a>
                    <a class="td-social-sharing-buttons td-social-twitter"
                       href="https://twitter.com/intent/tweet?text=<?php echo $content_detail['cont_title'] ?>&url=<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"><i
                            class=td-icon-twitter></i>
                        <div class=td-social-but-text>Twitter</div>
                    </a>
                    <a class="td-social-sharing-buttons td-social-google"
                       href="http://plus.google.com/share?url=<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                       onclick="window.open(this.href, 'mywin','left=50,top=50,width=600,height=350,toolbar=0'); return false;"><i
                            class=td-icon-googleplus></i></a>
                </div>
                <div class=td-classic-sharing>
                    <ul>
                        <li class=td-classic-facebook>
                            <iframe frameBorder=0
                                    src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>/&amp;layout=button_count&amp;show_faces=false&amp;width=105&amp;action=like&amp;colorscheme=light&amp;height=21"
                                    style="border:none;overflow:hidden;width:105px;height:21px;background-color:transparent">

                            </iframe>
                        </li>
                        <li class=td-classic-twitter>
                            <a href="https://twitter.com/share" class=twitter-share-button
                                                        data-url="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                                                        data-text="<?php echo $this->arrContent['cont_title'] ?>"
                                                        data-via="" data-lang=en>tweet</a>
                            <script>!function (d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (!d.getElementById(id)) {
                                        js = d.createElement(s);
                                        js.id = id;
                                        js.src = "http://platform.twitter.com/widgets.js";
                                        fjs.parentNode.insertBefore(js, fjs);
                                    }
                                }(document, "script", "twitter-wjs");</script>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="fb-comments"
                 data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>"
                 data-numposts="5">
            </div>
        </footer>
    </article>
    <div class="td_block_wrap td_block_related_posts  td-pb-border-top">
        <h4 class="td-related-content-title">
            <a href="javascript:;" class="more_content td-related-left td-cur-simple-item" data-type="#content_related">BÀI LIÊN QUAN</a>
            <a href="javascript:;" class="more_content td-related-right" data-type="#content_category">CÙNG DANH MỤC</a>
        </h4>
        <div id="content_related" class="show_content td_block_inner td_animated_xlong td_fadeInDown" style="height: auto;">
            <div class="td-related-row">
                <?php foreach ($this->arrContentLikeList as $content) { ?>
                <div class="td-related-span4">
                    <div class="td_module_related_posts td-animation-stack td_mod_related_posts">
                        <div class="td-module-image">
                            <div class="td-module-thumb">
                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>"
                                    rel="bookmark"
                                    title="<?php echo $content['cont_title'] ?>">
                                    <img width="218" height="150" class="entry-thumb td-animation-stack-type0-2"
                                        src="<?php echo $content['cont_main_image'] ?>"
                                        alt="<?php echo $content['cont_title'] ?>"
                                        title="<?php echo $content['cont_title'] ?>">
                                </a>
                            </div>
                            <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $list_category[$content['cate_id']]['cate_slug'], 'cateId' => $list_category[$content['cate_id']]['cate_id']]) ?>"
                               class="td-post-category">
                                <?php echo $list_category[$content['cate_id']]['cate_name'] ?>
                            </a>
                        </div>
                        <div class="item-details">
                            <h3 class="entry-title td-module-title">
                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>"
                                    rel="bookmark"
                                    title="<?php echo $content['cont_title'] ?>">
                                    <?php echo (strlen($content['cont_title']) < 60) ? $content['cont_title'] : mb_substr($content['cont_title'], 0, 60, 'UTF-8') . '...'; ?>
                                </a>
                            </h3>
                        </div>
                    </div>

                </div>
                <?php } ?>
            </div>
        </div>
        <div id="content_category" class="show_content td_block_inner td_animated_xlong td_fadeInDown" style="height: auto; display: none">
            <div class="td-related-row">
                <?php foreach ($this->arrContentCateList as $content) { ?>
                <div class="td-related-span4">
                    <div class="td_module_related_posts td-animation-stack td_mod_related_posts">
                        <div class="td-module-image">
                            <div class="td-module-thumb">
                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>"
                                    rel="bookmark" title="<?php echo $content['cont_title'] ?>">
                                    <img width="218" height="150" class="entry-thumb td-animation-stack-type0-2"
                                        src="<?php echo $content['cont_main_image'] ?>"
                                        alt="<?php echo $content['cont_title'] ?>"
                                         title="<?php echo $content['cont_title'] ?>">
                                </a>
                            </div>
                            <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $list_category[$content['cate_id']]['cate_slug'], 'cateId' => $list_category[$content['cate_id']]['cate_id']]) ?>" class="td-post-category">
                                <?php echo $list_category[$content['cate_id']]['cate_name'] ?>
                            </a>
                        </div>
                        <div class="item-details">
                            <h3 class="entry-title td-module-title">
                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>"
                                    rel="bookmark" title="<?php echo $content['cont_title'] ?>">
                                    <?php echo (strlen($content['cont_title']) < 60) ? $content['cont_title'] : mb_substr($content['cont_title'], 0, 60, 'UTF-8') . '...'; ?>

                                </a>
                            </h3>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery('.more_content').click(function(){
        var id = jQuery(this).data('type');
        jQuery('.show_content').hide();
        jQuery(id).show();
        jQuery('.more_content').removeClass('td-cur-simple-item');
        jQuery(this).addClass('td-cur-simple-item');
        return true;
    });
</script>