<?php
$arr_content = $this->arrContentList;
$content_main = $arr_content[0];
unset($arr_content[0]);
?>
<div class="content taxonomypage">
    <div class="slider">
        <ul>
            <li>
                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content_main['cont_slug'], 'contentId' => $content_main['cont_id']]) ?>">
                    <img class="thumb"
                         src="<?php echo $content_main['cont_main_image'] ?>"
                         alt="<?php echo trim($content_main['cont_title']) ?>"/>
                    <span><?php echo trim($content_main['cont_title']) ?></span>
                </a>
            </li>
        </ul>
    </div>


    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <!-- TT360 Responsive Article -->
        <ins class="adsbygoogle"
             style="display:inline-block;"
             data-ad-client="ca-pub-9166980393030854"
             data-ad-slot="5007199245"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div class="breadcrumbs-box">
        <div class="breadcrumbs info-detail">
                <span class="first breadcrumb">
                    <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>"></a>
                </span>
                <span typeof="v:Breadcrumb" class="breadcrumb">
                    <a rel="v:url" property="v:title" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' =>  $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id']]) ?>">
                        <?php echo $this->arrCategoryDetail['cate_name']; ?>
                    </a>
                </span>
        </div>
    </div>
    <div class="ListNews">
        <div class="listview clearfix">
            <ul>
                <?php foreach ($arr_content as $content) { ?>
                    <li class="listitem clearfix">
                        <a class="title" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                            <?php echo $content['cont_title'] ?>
                        </a>
                        <a class="thumb" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                            <img src="<?php echo $content['cont_resize_image'] ?>"
                                 alt="<?php echo $content['cont_title'] ?>"/>
                        </a>
                        <div class="desc"><?php echo $content['cont_description'] ?></div>

                        <!--                        <div class="user-info clearfix">-->
                        <!--                            <a class="user-link">-->
                        <!--                                <img class="user-avatar" src=""/>-->
                        <!--                            </a>-->
                        <!--                            <a class="user-name" data-uid="488"> Tuấn Phong</a>-->
                        <!--                            <span class="date"></span>-->
                        <!--                        </div>-->
                    </li>
                <?php } ?>
            </ul>
        </div>
        <div class="pagination-container">
            <ul class="pagination">
                <?php echo $this->paging; ?>
            </ul>
        </div>
    </div>
</div>
