<?php
$arr_new_content = unserialize(ARR_NEW_CONTENT);
$content_main = $arr_new_content[19];
?>
<div class="content">
    <div class="slider">
        <ul>
            <li>
                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content_main['cont_slug'], 'contentId' => $content_main['cont_id']]) ?>">
                    <img class="thumb"
                         src="<?php echo $content_main['cont_main_image'] ?>"
                         alt="<?php echo trim($content_main['cont_title']) ?>"/>
                    <span><?php echo trim($content_main['cont_title']) ?></span>
                </a>
            </li>
        </ul>
    </div>


    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <!-- QTM Responsive Article -->
        <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
            <!-- TT360 Category -->
            <ins class="adsbygoogle"
                 style="display:inline-block;"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="5007199245"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>

    </div>
    <div class="ListNews">
        <div class="listview clearfix">
            <ul>
                <?php for ($i = 18; $i >=0; $i --){ ?>
                    <li class="listitem clearfix">
                        <a class="title" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_new_content[$i]['cont_slug'], 'contentId' => $arr_new_content[$i]['cont_id']]) ?>">
                            <?php echo $arr_new_content[$i]['cont_title'] ?>
                        </a>
                        <a class="thumb" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_new_content[$i]['cont_slug'], 'contentId' => $arr_new_content[$i]['cont_id']]) ?>">
                            <img src="<?php echo $arr_new_content[$i]['cont_resize_image'] ?>"
                                 alt="<?php echo $arr_new_content[$i]['cont_title'] ?>"/>
                        </a>
                        <div class="desc"><?php echo $arr_new_content[$i]['cont_description'] ?></div>

<!--                        <div class="user-info clearfix">-->
<!--                            <a class="user-link">-->
<!--                                <img class="user-avatar" src=""/>-->
<!--                            </a>-->
<!--                            <a class="user-name" data-uid="488"> Tuấn Phong</a>-->
<!--                            <span class="date"></span>-->
<!--                        </div>-->
                    </li>
                <?php } ?>
            </ul>
        </div>
        <a class="viewmore" href="#">Xem thêm</a>
    </div>
</div>
