<div class="vc_row wpb_row td-pb-row td-ss-row">
    <div class="wpb_column vc_column_container td-pb-span8">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_1 td_uid_18_5804cf95597ef_rand td_with_ajax_pagination td-pb-border-top"
                     data-td-block-uid=td_uid_18_5804cf95597ef>
                    <style scoped>.td_uid_18_5804cf95597ef_rand .td_module_wrap:hover .entry-title a, .td_uid_18_5804cf95597ef_rand a.td-pulldown-filter-link:hover, .td_uid_18_5804cf95597ef_rand .td-subcat-item a:hover, .td_uid_18_5804cf95597ef_rand .td-subcat-item .td-cur-simple-item, .td_uid_18_5804cf95597ef_rand .td_quote_on_blocks, .td_uid_18_5804cf95597ef_rand .td-opacity-cat .td-post-category:hover, .td_uid_18_5804cf95597ef_rand .td-opacity-read .td-read-more a:hover, .td_uid_18_5804cf95597ef_rand .td-opacity-author .td-post-author-name a:hover, .td_uid_18_5804cf95597ef_rand .td-instagram-user a {
                            color: #f9c100
                        }

                        .td_uid_18_5804cf95597ef_rand .td-next-prev-wrap a:hover, .td_uid_18_5804cf95597ef_rand .td-load-more-wrap a:hover {
                            background-color: #f9c100;
                            border-color: #f9c100
                        }

                        .td_uid_18_5804cf95597ef_rand .block-title span, .td_uid_18_5804cf95597ef_rand .td-trending-now-title, .td_uid_18_5804cf95597ef_rand .block-title a, .td_uid_18_5804cf95597ef_rand .td-read-more a, .td_uid_18_5804cf95597ef_rand .td-weather-information:before, .td_uid_18_5804cf95597ef_rand .td-weather-week:before, .td_uid_18_5804cf95597ef_rand .td-subcat-dropdown:hover .td-subcat-more, .td_uid_18_5804cf95597ef_rand .td-exchange-header:before, .td_uid_18_5804cf95597ef_rand .td-post-category:hover {
                            background-color: #f9c100
                        }

                        .td_uid_18_5804cf95597ef_rand .block-title {
                            border-color: #f9c100
                        }</style>
                    <script>var block_td_uid_18_5804cf95597ef = new tdBlock();
                        block_td_uid_18_5804cf95597ef.id = "td_uid_18_5804cf95597ef";
                        block_td_uid_18_5804cf95597ef.atts = '{"limit":5,"sort":"popular","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"","category_ids":"-2","custom_title":"DON\u0027T MISS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"#f9c100","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":2,"td_ajax_preloading":"","td_ajax_filter_type":"td_category_ids_filter","td_ajax_filter_ids":"10, 9, 19, 17, 13, 24, 12, 14, 15, 27, 26, 18","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_18_5804cf95597ef_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_18_5804cf95597ef.td_column_number = "2";
                        block_td_uid_18_5804cf95597ef.block_type = "td_block_1";
                        block_td_uid_18_5804cf95597ef.post_count = "5";
                        block_td_uid_18_5804cf95597ef.found_posts = "144";
                        block_td_uid_18_5804cf95597ef.header_color = "#f9c100";
                        block_td_uid_18_5804cf95597ef.ajax_pagination_infinite_stop = "";
                        block_td_uid_18_5804cf95597ef.max_num_pages = "29";
                        tdBlocksArray.push(block_td_uid_18_5804cf95597ef);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>DON&#039;T MISS</span></h4>
                        <div class=td-subcat-filter id=td_pulldown_td_uid_18_5804cf95597ef>
                            <ul class=td-subcat-list id=td_pulldown_td_uid_18_5804cf95597ef_list>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_19_5804cf955ba0f
                                                            data-td_filter_value=""
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">All</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_20_5804cf955ba4a
                                                            data-td_filter_value=10
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Style hunter</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_21_5804cf955ba83
                                                            data-td_filter_value=9
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Vogue</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_22_5804cf955babb
                                                            data-td_filter_value=19
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Health &amp; Fitness</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_23_5804cf955baf4
                                                            data-td_filter_value=17
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Travel</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_24_5804cf955bb2f
                                                            data-td_filter_value=13
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Gadgets</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_25_5804cf955bb6c
                                                            data-td_filter_value=24
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">WRC Racing</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_26_5804cf955bbaa
                                                            data-td_filter_value=12
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Reviews</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_27_5804cf955bbe7
                                                            data-td_filter_value=14
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Mobile and Phones</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_28_5804cf955bc24
                                                            data-td_filter_value=15
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Photography</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_29_5804cf955bc62
                                                            data-td_filter_value=27
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Make it modern</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_30_5804cf955bc9f
                                                            data-td_filter_value=26
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Decorating</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_31_5804cf955bcdc
                                                            data-td_filter_value=18
                                                            data-td_block_id=td_uid_18_5804cf95597ef
                                                            href="#">Recipes</a></li>
                            </ul>
                            <div class=td-subcat-dropdown>
                                <div class=td-subcat-more aria-haspopup=true><span>More</span><i
                                        class=td-icon-read-down></i></div>
                                <ul class=td-pulldown-filter-list></ul>
                            </div>
                        </div>
                    </div>
                    <div id=td_uid_18_5804cf95597ef class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="10-landscapes-wont-even-imagined-exist/index.html"
                                                rel=bookmark
                                                title="10 Landscapes You Won’t Have Even Imagined Exist"><img
                                                    width=324 height=235 class=entry-thumb
                                                    src="wp-content/uploads/2015/03/travel-girl-324x235.jpg"
                                                    alt=""
                                                    title="10 Landscapes You Won’t Have Even Imagined Exist"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-travel/index.html"
                                           class=td-post-category>Travel</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="10-landscapes-wont-even-imagined-exist/index.html"
                                            rel=bookmark
                                            title="10 Landscapes You Won’t Have Even Imagined Exist">10
                                            Landscapes You Won’t Have Even Imagined Exist</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-03-22T05:47:34+00:00">Mar 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="10-landscapes-wont-even-imagined-exist/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Prince Edward Island, Canada
                                        Prince Edward Island is a Canadian province. It is one of the three
                                        Maritime provinces and it is the smallest in...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                            rel=bookmark
                                            title="Decorating to Celebrate the Great Outdoor Space"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/01/outside-100x70.jpg" alt=""
                                                title="Decorating to Celebrate the Great Outdoor Space"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                                rel=bookmark
                                                title="Decorating to Celebrate the Great Outdoor Space">Decorating
                                                to Celebrate the Great Outdoor Space</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-01-22T05:46:01+00:00">Jan 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                            rel=bookmark
                                            title="Zeta Architecture: Hexagon is the new circle in 2016"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/01/house-interior-100x70.jpg"
                                                alt=""
                                                title="Zeta Architecture: Hexagon is the new circle in 2016"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                                rel=bookmark
                                                title="Zeta Architecture: Hexagon is the new circle in 2016">Zeta
                                                Architecture: Hexagon is the new circle in 2016</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-01-22T05:44:07+00:00">Jan 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-what-do-i-need-to-make-it-in-business/index.html"
                                            rel=bookmark title="What Do I Need To Make It In Business?"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/bag-100x70.jpg" alt=""
                                                title="What Do I Need To Make It In Business?"/></a></div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-what-do-i-need-to-make-it-in-business/index.html"
                                                rel=bookmark title="What Do I Need To Make It In Business?">What
                                                Do I Need To Make It In Business?</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-21T06:15:43+00:00">Apr 21, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-planning-a-winter-holiday-canary-islands-offers-the-best-value-getaway-this-season/index.html"
                                            rel=bookmark
                                            title="Planning a winter holiday? Canary Islands offers"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/03/boat-100x70.jpg" alt=""
                                                title="Planning a winter holiday? Canary Islands offers"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-planning-a-winter-holiday-canary-islands-offers-the-best-value-getaway-this-season/index.html"
                                                rel=bookmark
                                                title="Planning a winter holiday? Canary Islands offers">Planning
                                                a winter holiday? Canary Islands offers</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-03-22T05:45:36+00:00">Mar 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                                    id=prev-page-td_uid_18_5804cf95597ef
                                                    data-td_block_id=td_uid_18_5804cf95597ef><i
                                class="td-icon-font td-icon-menu-left"></i></a><a href="#"
                                                                                  class=td-ajax-next-page
                                                                                  id=next-page-td_uid_18_5804cf95597ef
                                                                                  data-td_block_id=td_uid_18_5804cf95597ef><i
                                class="td-icon-font td-icon-menu-right"></i></a></div>
                </div>
                <div class="td_block_wrap td_block_2 td_uid_32_5804cf955e5fb_rand td_with_ajax_pagination td-pb-border-top"
                     data-td-block-uid=td_uid_32_5804cf955e5fb>
                    <style scoped>.td_uid_32_5804cf955e5fb_rand .td_module_wrap:hover .entry-title a, .td_uid_32_5804cf955e5fb_rand a.td-pulldown-filter-link:hover, .td_uid_32_5804cf955e5fb_rand .td-subcat-item a:hover, .td_uid_32_5804cf955e5fb_rand .td-subcat-item .td-cur-simple-item, .td_uid_32_5804cf955e5fb_rand .td_quote_on_blocks, .td_uid_32_5804cf955e5fb_rand .td-opacity-cat .td-post-category:hover, .td_uid_32_5804cf955e5fb_rand .td-opacity-read .td-read-more a:hover, .td_uid_32_5804cf955e5fb_rand .td-opacity-author .td-post-author-name a:hover, .td_uid_32_5804cf955e5fb_rand .td-instagram-user a {
                            color: #4caf50
                        }

                        .td_uid_32_5804cf955e5fb_rand .td-next-prev-wrap a:hover, .td_uid_32_5804cf955e5fb_rand .td-load-more-wrap a:hover {
                            background-color: #4caf50;
                            border-color: #4caf50
                        }

                        .td_uid_32_5804cf955e5fb_rand .block-title span, .td_uid_32_5804cf955e5fb_rand .td-trending-now-title, .td_uid_32_5804cf955e5fb_rand .block-title a, .td_uid_32_5804cf955e5fb_rand .td-read-more a, .td_uid_32_5804cf955e5fb_rand .td-weather-information:before, .td_uid_32_5804cf955e5fb_rand .td-weather-week:before, .td_uid_32_5804cf955e5fb_rand .td-subcat-dropdown:hover .td-subcat-more, .td_uid_32_5804cf955e5fb_rand .td-exchange-header:before, .td_uid_32_5804cf955e5fb_rand .td-post-category:hover {
                            background-color: #4caf50
                        }

                        .td_uid_32_5804cf955e5fb_rand .block-title {
                            border-color: #4caf50
                        }</style>
                    <script>var block_td_uid_32_5804cf955e5fb = new tdBlock();
                        block_td_uid_32_5804cf955e5fb.id = "td_uid_32_5804cf955e5fb";
                        block_td_uid_32_5804cf955e5fb.atts = '{"limit":"6","sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"16","category_ids":"16, -2","custom_title":"LIFESTYLE NEWS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"#4caf50","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":2,"td_ajax_preloading":"","td_ajax_filter_type":"td_category_ids_filter","td_ajax_filter_ids":"17, 18, 19, 20","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_32_5804cf955e5fb_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_32_5804cf955e5fb.td_column_number = "2";
                        block_td_uid_32_5804cf955e5fb.block_type = "td_block_2";
                        block_td_uid_32_5804cf955e5fb.post_count = "6";
                        block_td_uid_32_5804cf955e5fb.found_posts = "28";
                        block_td_uid_32_5804cf955e5fb.header_color = "#4caf50";
                        block_td_uid_32_5804cf955e5fb.ajax_pagination_infinite_stop = "";
                        block_td_uid_32_5804cf955e5fb.max_num_pages = "5";
                        tdBlocksArray.push(block_td_uid_32_5804cf955e5fb);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>LIFESTYLE NEWS</span></h4>
                        <div class=td-subcat-filter id=td_pulldown_td_uid_32_5804cf955e5fb>
                            <ul class=td-subcat-list id=td_pulldown_td_uid_32_5804cf955e5fb_list>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_33_5804cf955f091
                                                            data-td_filter_value=""
                                                            data-td_block_id=td_uid_32_5804cf955e5fb
                                                            href="#">All</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_34_5804cf955f0cb
                                                            data-td_filter_value=17
                                                            data-td_block_id=td_uid_32_5804cf955e5fb
                                                            href="#">Travel</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_35_5804cf955f103
                                                            data-td_filter_value=18
                                                            data-td_block_id=td_uid_32_5804cf955e5fb
                                                            href="#">Recipes</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_36_5804cf955f13b
                                                            data-td_filter_value=19
                                                            data-td_block_id=td_uid_32_5804cf955e5fb
                                                            href="#">Health &amp; Fitness</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_37_5804cf955f173
                                                            data-td_filter_value=20
                                                            data-td_block_id=td_uid_32_5804cf955e5fb
                                                            href="#">Business</a></li>
                            </ul>
                            <div class=td-subcat-dropdown>
                                <div class=td-subcat-more aria-haspopup=true><span>More</span><i
                                        class=td-icon-read-down></i></div>
                                <ul class=td-pulldown-filter-list></ul>
                            </div>
                        </div>
                    </div>
                    <div id=td_uid_32_5804cf955e5fb class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_2 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="whitewater-rafting-day-trip-new-york-east/index.html"
                                                rel=bookmark
                                                title="Whitewater Rafting Day Trip from New York in the East"><img
                                                    width=324 height=160 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/green-house-324x160.jpg"
                                                    alt=""
                                                    title="Whitewater Rafting Day Trip from New York in the East"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-business/index.html"
                                           class=td-post-category>Business</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="whitewater-rafting-day-trip-new-york-east/index.html"
                                            rel=bookmark
                                            title="Whitewater Rafting Day Trip from New York in the East">Whitewater
                                            Rafting Day Trip from New York in the East</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T06:23:44+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="whitewater-rafting-day-trip-new-york-east/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Whitewater Rafting Day Trip from NYC
                                        Meet at West 45th Street and 11th Avenue and board the bus for
                                        world-renowned Hunter Mountain. Many...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_2 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html"
                                                rel=bookmark
                                                title="Five things you may have missed over the weekend from the world of business"><img
                                                    width=324 height=160 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/green-324x160.jpg" alt=""
                                                    title="Five things you may have missed over the weekend from the world of business"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-business/index.html"
                                           class=td-post-category>Business</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html"
                                            rel=bookmark
                                            title="Five things you may have missed over the weekend from the world of business">Five
                                            things you may have missed over the weekend from the...</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T06:23:43+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot...
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-express-recipes-how-to-make-creamy-papaya-raita/index.html"
                                            rel=bookmark
                                            title="Express Recipes: How to make Creamy Papaya Raita"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/green-girl-100x70.jpg" alt=""
                                                title="Express Recipes: How to make Creamy Papaya Raita"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-express-recipes-how-to-make-creamy-papaya-raita/index.html"
                                                rel=bookmark
                                                title="Express Recipes: How to make Creamy Papaya Raita">Express
                                                Recipes: How to make Creamy Papaya Raita</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T06:23:33+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html"
                                            rel=bookmark
                                            title="400k for whisky? Most expensive foods and drink auctioned"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/65-100x70.jpg" alt=""
                                                title="400k for whisky? Most expensive foods and drink auctioned"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html"
                                                rel=bookmark
                                                title="400k for whisky? Most expensive foods and drink auctioned">400k
                                                for whisky? Most expensive foods and drink auctioned</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:42+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-seeking-business-cuomo-heads-to-cuba-with-a-new-york-trade-delegation/index.html"
                                            rel=bookmark
                                            title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/66-100x70.jpg" alt=""
                                                title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-seeking-business-cuomo-heads-to-cuba-with-a-new-york-trade-delegation/index.html"
                                                rel=bookmark
                                                title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation">Seeking
                                                Business, Cuomo Heads to Cuba With a New York Trade...</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:42+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-food-health-star-ratings-kelloggs-reveals-the-cereal-that-gets-1-5-stars/index.html"
                                            rel=bookmark
                                            title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/64-100x70.jpg" alt=""
                                                title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-food-health-star-ratings-kelloggs-reveals-the-cereal-that-gets-1-5-stars/index.html"
                                                rel=bookmark
                                                title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars">Food
                                                health star ratings: Kellogg&#8217;s reveals the cereal that
                                                gets 1.5...</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:41+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                                    id=prev-page-td_uid_32_5804cf955e5fb
                                                    data-td_block_id=td_uid_32_5804cf955e5fb><i
                                class="td-icon-font td-icon-menu-left"></i></a><a href="#"
                                                                                  class=td-ajax-next-page
                                                                                  id=next-page-td_uid_32_5804cf955e5fb
                                                                                  data-td_block_id=td_uid_32_5804cf955e5fb><i
                                class="td-icon-font td-icon-menu-right"></i></a></div>
                </div>
                <div class="td_block_wrap td_block_15 td_uid_38_5804cf9563362_rand td_with_ajax_pagination td-pb-border-top"
                     data-td-block-uid=td_uid_38_5804cf9563362>
                    <style scoped>.td_uid_38_5804cf9563362_rand .td_module_wrap:hover .entry-title a, .td_uid_38_5804cf9563362_rand a.td-pulldown-filter-link:hover, .td_uid_38_5804cf9563362_rand .td-subcat-item a:hover, .td_uid_38_5804cf9563362_rand .td-subcat-item .td-cur-simple-item, .td_uid_38_5804cf9563362_rand .td_quote_on_blocks, .td_uid_38_5804cf9563362_rand .td-opacity-cat .td-post-category:hover, .td_uid_38_5804cf9563362_rand .td-opacity-read .td-read-more a:hover, .td_uid_38_5804cf9563362_rand .td-opacity-author .td-post-author-name a:hover, .td_uid_38_5804cf9563362_rand .td-instagram-user a {
                            color: #607d8b
                        }

                        .td_uid_38_5804cf9563362_rand .td-next-prev-wrap a:hover, .td_uid_38_5804cf9563362_rand .td-load-more-wrap a:hover {
                            background-color: #607d8b;
                            border-color: #607d8b
                        }

                        .td_uid_38_5804cf9563362_rand .block-title span, .td_uid_38_5804cf9563362_rand .td-trending-now-title, .td_uid_38_5804cf9563362_rand .block-title a, .td_uid_38_5804cf9563362_rand .td-read-more a, .td_uid_38_5804cf9563362_rand .td-weather-information:before, .td_uid_38_5804cf9563362_rand .td-weather-week:before, .td_uid_38_5804cf9563362_rand .td-subcat-dropdown:hover .td-subcat-more, .td_uid_38_5804cf9563362_rand .td-exchange-header:before, .td_uid_38_5804cf9563362_rand .td-post-category:hover {
                            background-color: #607d8b
                        }

                        .td_uid_38_5804cf9563362_rand .block-title {
                            border-color: #607d8b
                        }</style>
                    <script>var block_td_uid_38_5804cf9563362 = new tdBlock();
                        block_td_uid_38_5804cf9563362.id = "td_uid_38_5804cf9563362";
                        block_td_uid_38_5804cf9563362.atts = '{"limit":"3","sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"25","category_ids":"","custom_title":"HOUSE DESIGN","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"#607d8b","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":2,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_38_5804cf9563362_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_38_5804cf9563362.td_column_number = "2";
                        block_td_uid_38_5804cf9563362.block_type = "td_block_15";
                        block_td_uid_38_5804cf9563362.post_count = "3";
                        block_td_uid_38_5804cf9563362.found_posts = "34";
                        block_td_uid_38_5804cf9563362.header_color = "#607d8b";
                        block_td_uid_38_5804cf9563362.ajax_pagination_infinite_stop = "";
                        block_td_uid_38_5804cf9563362.max_num_pages = "12";
                        tdBlocksArray.push(block_td_uid_38_5804cf9563362);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>HOUSE DESIGN</span></h4>
                    </div>
                    <div id=td_uid_38_5804cf9563362 class="td_block_inner td-column-2">
                        <div class=td-block-row>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                                rel=bookmark
                                                title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/119-218x150.jpg" alt=""
                                                    title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-interiors/index.html"
                                           class=td-post-category>Interiors</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                            rel=bookmark
                                            title="Patricia Urquiola transparent furniture for Glas Italia with iridescent">Patricia
                                            Urquiola transparent furniture for Glas Italia with iridescent</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                                rel=bookmark
                                                title="Denton Corker Marshall the mysterious black box is biennale pavilion"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/115-218x150.jpg" alt=""
                                                    title="Denton Corker Marshall the mysterious black box is biennale pavilion"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                            rel=bookmark
                                            title="Denton Corker Marshall the mysterious black box is biennale pavilion">Denton
                                            Corker Marshall the mysterious black box is biennale pavilion</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                                rel=bookmark
                                                title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/107-218x150.jpg" alt=""
                                                    title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                            rel=bookmark
                                            title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job">Man
                                            agrees to complete $5,000 Hereford Inlet Lighthouse painting job</a>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                                    id=prev-page-td_uid_38_5804cf9563362
                                                    data-td_block_id=td_uid_38_5804cf9563362><i
                                class="td-icon-font td-icon-menu-left"></i></a><a href="#"
                                                                                  class=td-ajax-next-page
                                                                                  id=next-page-td_uid_38_5804cf9563362
                                                                                  data-td_block_id=td_uid_38_5804cf9563362><i
                                class="td-icon-font td-icon-menu-right"></i></a></div>
                </div>
                <div class="td_block_wrap td_block_1 td_uid_39_5804cf9564e32_rand td_with_ajax_pagination td-pb-border-top"
                     data-td-block-uid=td_uid_39_5804cf9564e32>
                    <style scoped>.td_uid_39_5804cf9564e32_rand .td_module_wrap:hover .entry-title a, .td_uid_39_5804cf9564e32_rand a.td-pulldown-filter-link:hover, .td_uid_39_5804cf9564e32_rand .td-subcat-item a:hover, .td_uid_39_5804cf9564e32_rand .td-subcat-item .td-cur-simple-item, .td_uid_39_5804cf9564e32_rand .td_quote_on_blocks, .td_uid_39_5804cf9564e32_rand .td-opacity-cat .td-post-category:hover, .td_uid_39_5804cf9564e32_rand .td-opacity-read .td-read-more a:hover, .td_uid_39_5804cf9564e32_rand .td-opacity-author .td-post-author-name a:hover, .td_uid_39_5804cf9564e32_rand .td-instagram-user a {
                            color: #f44336
                        }

                        .td_uid_39_5804cf9564e32_rand .td-next-prev-wrap a:hover, .td_uid_39_5804cf9564e32_rand .td-load-more-wrap a:hover {
                            background-color: #f44336;
                            border-color: #f44336
                        }

                        .td_uid_39_5804cf9564e32_rand .block-title span, .td_uid_39_5804cf9564e32_rand .td-trending-now-title, .td_uid_39_5804cf9564e32_rand .block-title a, .td_uid_39_5804cf9564e32_rand .td-read-more a, .td_uid_39_5804cf9564e32_rand .td-weather-information:before, .td_uid_39_5804cf9564e32_rand .td-weather-week:before, .td_uid_39_5804cf9564e32_rand .td-subcat-dropdown:hover .td-subcat-more, .td_uid_39_5804cf9564e32_rand .td-exchange-header:before, .td_uid_39_5804cf9564e32_rand .td-post-category:hover {
                            background-color: #f44336
                        }

                        .td_uid_39_5804cf9564e32_rand .block-title {
                            border-color: #f44336
                        }</style>
                    <script>var block_td_uid_39_5804cf9564e32 = new tdBlock();
                        block_td_uid_39_5804cf9564e32.id = "td_uid_39_5804cf9564e32";
                        block_td_uid_39_5804cf9564e32.atts = '{"limit":5,"sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"11","category_ids":"","custom_title":"TECH AND GADGETS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"#f44336","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":2,"td_ajax_preloading":"","td_ajax_filter_type":"td_category_ids_filter","td_ajax_filter_ids":"13, 14, 15, 12","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_39_5804cf9564e32_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_39_5804cf9564e32.td_column_number = "2";
                        block_td_uid_39_5804cf9564e32.block_type = "td_block_1";
                        block_td_uid_39_5804cf9564e32.post_count = "5";
                        block_td_uid_39_5804cf9564e32.found_posts = "33";
                        block_td_uid_39_5804cf9564e32.header_color = "#f44336";
                        block_td_uid_39_5804cf9564e32.ajax_pagination_infinite_stop = "";
                        block_td_uid_39_5804cf9564e32.max_num_pages = "7";
                        tdBlocksArray.push(block_td_uid_39_5804cf9564e32);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>TECH AND GADGETS</span></h4>
                        <div class=td-subcat-filter id=td_pulldown_td_uid_39_5804cf9564e32>
                            <ul class=td-subcat-list id=td_pulldown_td_uid_39_5804cf9564e32_list>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_40_5804cf95662c3
                                                            data-td_filter_value=""
                                                            data-td_block_id=td_uid_39_5804cf9564e32
                                                            href="#">All</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_41_5804cf95662fd
                                                            data-td_filter_value=13
                                                            data-td_block_id=td_uid_39_5804cf9564e32
                                                            href="#">Gadgets</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_42_5804cf9566336
                                                            data-td_filter_value=14
                                                            data-td_block_id=td_uid_39_5804cf9564e32
                                                            href="#">Mobile and Phones</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_43_5804cf956636e
                                                            data-td_filter_value=15
                                                            data-td_block_id=td_uid_39_5804cf9564e32
                                                            href="#">Photography</a></li>
                                <li class=td-subcat-item><a class=td-subcat-link id=td_uid_44_5804cf95663a7
                                                            data-td_filter_value=12
                                                            data-td_block_id=td_uid_39_5804cf9564e32
                                                            href="#">Reviews</a></li>
                            </ul>
                            <div class=td-subcat-dropdown>
                                <div class=td-subcat-more aria-haspopup=true><span>More</span><i
                                        class=td-icon-read-down></i></div>
                                <ul class=td-pulldown-filter-list></ul>
                            </div>
                        </div>
                    </div>
                    <div id=td_uid_39_5804cf9564e32 class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html"
                                                rel=bookmark
                                                title="Amazon&#8217;s Apple Watch killer will be free and sell you everything"><img
                                                    width=324 height=235 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/headphones-324x235.jpg"
                                                    alt=""
                                                    title="Amazon&#8217;s Apple Watch killer will be free and sell you everything"/></a>
                                        </div>
                                        <a href="category/tagdiv-technology/index.html"
                                           class=td-post-category>Technology</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html"
                                            rel=bookmark
                                            title="Amazon&#8217;s Apple Watch killer will be free and sell you everything">Amazon&#8217;s
                                            Apple Watch killer will be free and sell you everything</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-24T05:44:22+00:00">Apr 24, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-microsoft-subsumes-open-tech-unit-back-inside-mothership/index.html"
                                            rel=bookmark
                                            title="Microsoft Subsumes Open Tech Unit Back Inside Mothership"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/tee-100x70.jpg" alt=""
                                                title="Microsoft Subsumes Open Tech Unit Back Inside Mothership"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-microsoft-subsumes-open-tech-unit-back-inside-mothership/index.html"
                                                rel=bookmark
                                                title="Microsoft Subsumes Open Tech Unit Back Inside Mothership">Microsoft
                                                Subsumes Open Tech Unit Back Inside Mothership</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-24T05:23:25+00:00">Apr 24, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                            rel=bookmark
                                            title="Why tech accelerators may soon be as irrelevant as an MBA"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/singer-100x70.jpg" alt=""
                                                title="Why tech accelerators may soon be as irrelevant as an MBA"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                                rel=bookmark
                                                title="Why tech accelerators may soon be as irrelevant as an MBA">Why
                                                tech accelerators may soon be as irrelevant as an MBA</a></h3>
                                        <div class=td-module-meta-info>
                                            <div class=entry-review-stars><i class=td-icon-star></i><i
                                                    class=td-icon-star></i><i class=td-icon-star></i><i
                                                    class=td-icon-star></i><i class=td-icon-star-empty></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-canon-xc10-4k-digital-camcorder-is-out-compact-versatile-and-for-only-2500/index.html"
                                            rel=bookmark
                                            title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/snickers-100x70.jpg" alt=""
                                                title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-canon-xc10-4k-digital-camcorder-is-out-compact-versatile-and-for-only-2500/index.html"
                                                rel=bookmark
                                                title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile">Canon
                                                XC10 4K Digital Camcorder Is Out: Compact and Versatile</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:32+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-part-gopro-dropcam-flir-fx-camera-does-sports-a-new-camera/index.html"
                                            rel=bookmark
                                            title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/43-100x70.jpg" alt=""
                                                title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-part-gopro-dropcam-flir-fx-camera-does-sports-a-new-camera/index.html"
                                                rel=bookmark
                                                title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera">Part
                                                GoPro Dropcam: Flir FX Camera Does Sports a new camera</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:31+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                                    id=prev-page-td_uid_39_5804cf9564e32
                                                    data-td_block_id=td_uid_39_5804cf9564e32><i
                                class="td-icon-font td-icon-menu-left"></i></a><a href="#"
                                                                                  class=td-ajax-next-page
                                                                                  id=next-page-td_uid_39_5804cf9564e32
                                                                                  data-td_block_id=td_uid_39_5804cf9564e32><i
                                class="td-icon-font td-icon-menu-right"></i></a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_social_counter td_uid_45_5804cf9569116_rand td-pb-border-top">
                    <h4 class=block-title><span>STAY CONNECTED</span></h4>
                    <div class=td-social-list>
                        <div class="td_social_type td-pb-margin-side td_social_facebook">
                            <div class=td-social-box>
                                <div class="td-sp td-sp-facebook"></div>
                                <span class=td_social_info>2,490</span><span
                                    class="td_social_info td_social_info_name">Fans</span><span
                                    class=td_social_button><a
                                        href="https://www.facebook.com/tagDiv">Like</a></span></div>
                        </div>
                        <div class="td_social_type td-pb-margin-side td_social_twitter">
                            <div class=td-social-box>
                                <div class="td-sp td-sp-twitter"></div>
                                <span class=td_social_info>535</span><span
                                    class="td_social_info td_social_info_name">Followers</span><span
                                    class=td_social_button><a
                                        href="https://twitter.com/tagDiv">Follow</a></span></div>
                        </div>
                        <div class="td_social_type td-pb-margin-side td_social_youtube">
                            <div class=td-social-box>
                                <div class="td-sp td-sp-youtube"></div>
                                <span class=td_social_info>11,900</span><span
                                    class="td_social_info td_social_info_name">Subscribers</span><span
                                    class=td_social_button><a
                                        href="http://www.youtube.com/envato">Subscribe</a></span></div>
                        </div>
                        <div class=clearfix></div>
                    </div>
                </div>
                <div class="td-a-rec td-a-rec-id-sidebar  "><span
                        class=td-adspot-title>- Advertisement -</span>
                    <div class=td-visible-desktop>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-landscape>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-portrait>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:200px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec200.jpg"
                                                                                     alt="" width=200
                                                                                     height=200/></a>
                    </div>
                    <div class=td-visible-phone>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                </div>
                <div class="td_block_wrap td_block_15 td_uid_47_5804cf956927f_rand td_with_ajax_pagination td-pb-border-top"
                     data-td-block-uid=td_uid_47_5804cf956927f>
                    <script>var block_td_uid_47_5804cf956927f = new tdBlock();
                        block_td_uid_47_5804cf956927f.id = "td_uid_47_5804cf956927f";
                        block_td_uid_47_5804cf956927f.atts = '{"limit":"4","sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"27","category_ids":"","custom_title":"MAKE IT MODERN","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_47_5804cf956927f_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_47_5804cf956927f.td_column_number = "1";
                        block_td_uid_47_5804cf956927f.block_type = "td_block_15";
                        block_td_uid_47_5804cf956927f.post_count = "4";
                        block_td_uid_47_5804cf956927f.found_posts = "12";
                        block_td_uid_47_5804cf956927f.header_color = "";
                        block_td_uid_47_5804cf956927f.ajax_pagination_infinite_stop = "";
                        block_td_uid_47_5804cf956927f.max_num_pages = "3";
                        tdBlocksArray.push(block_td_uid_47_5804cf956927f);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>MAKE IT MODERN</span></h4>
                    </div>
                    <div id=td_uid_47_5804cf956927f class="td_block_inner td-column-1">
                        <div class=td-block-span12>
                            <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-rosie-huntington-whiteley-talks-beauty-habits-career-ambitions-and-going-nude-for-art/index.html"
                                            rel=bookmark
                                            title="Rosie Huntington Whiteley Talks Beauty Habits Career Art"><img
                                                width=218 height=150 class=entry-thumb
                                                src="wp-content/uploads/2015/04/108-218x150.jpg" alt=""
                                                title="Rosie Huntington Whiteley Talks Beauty Habits Career Art"/></a>
                                    </div>
                                    <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                       class=td-post-category>Make it modern</a></div>
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-rosie-huntington-whiteley-talks-beauty-habits-career-ambitions-and-going-nude-for-art/index.html"
                                        rel=bookmark
                                        title="Rosie Huntington Whiteley Talks Beauty Habits Career Art">Rosie
                                        Huntington Whiteley Talks Beauty Habits Career Art</a></h3>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-bayside-ranch-a-perfect-canvas-for-interior-designer-2016/index.html"
                                            rel=bookmark
                                            title="Bayside Ranch a perfect canvas for interior designer 2016"><img
                                                width=218 height=150 class=entry-thumb
                                                src="wp-content/uploads/2015/04/109-218x150.jpg" alt=""
                                                title="Bayside Ranch a perfect canvas for interior designer 2016"/></a>
                                    </div>
                                    <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                       class=td-post-category>Make it modern</a></div>
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-bayside-ranch-a-perfect-canvas-for-interior-designer-2016/index.html"
                                        rel=bookmark
                                        title="Bayside Ranch a perfect canvas for interior designer 2016">Bayside
                                        Ranch a perfect canvas for interior designer 2016</a></h3>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                            rel=bookmark
                                            title="2016 Decorators opens with home design inspiration"><img
                                                width=218 height=150 class=entry-thumb
                                                src="wp-content/uploads/2015/04/house-218x150.jpg" alt=""
                                                title="2016 Decorators opens with home design inspiration"/></a>
                                    </div>
                                    <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                       class=td-post-category>Make it modern</a></div>
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                        rel=bookmark
                                        title="2016 Decorators opens with home design inspiration">2016
                                        Decorators opens with home design inspiration</a></h3>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                            rel=bookmark
                                            title="Artist brings air of distinction to Delafield apartment"><img
                                                width=218 height=150 class=entry-thumb
                                                src="wp-content/uploads/2015/04/110-218x150.jpg" alt=""
                                                title="Artist brings air of distinction to Delafield apartment"/></a>
                                    </div>
                                    <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                       class=td-post-category>Make it modern</a></div>
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                        rel=bookmark
                                        title="Artist brings air of distinction to Delafield apartment">Artist
                                        brings air of distinction to Delafield apartment</a></h3>
                            </div>
                        </div>
                    </div>
                    <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                                    id=prev-page-td_uid_47_5804cf956927f
                                                    data-td_block_id=td_uid_47_5804cf956927f><i
                                class="td-icon-font td-icon-menu-left"></i></a><a href="#"
                                                                                  class=td-ajax-next-page
                                                                                  id=next-page-td_uid_47_5804cf956927f
                                                                                  data-td_block_id=td_uid_47_5804cf956927f><i
                                class="td-icon-font td-icon-menu-right"></i></a></div>
                </div>
                <div class="td_block_wrap td_block_1 td_uid_48_5804cf956cd7d_rand td-pb-border-top"
                     data-td-block-uid=td_uid_48_5804cf956cd7d>
                    <script>var block_td_uid_48_5804cf956cd7d = new tdBlock();
                        block_td_uid_48_5804cf956cd7d.id = "td_uid_48_5804cf956cd7d";
                        block_td_uid_48_5804cf956cd7d.atts = '{"limit":"3","sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"12","category_ids":"","custom_title":"LATEST REVIEWS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_48_5804cf956cd7d_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_48_5804cf956cd7d.td_column_number = "1";
                        block_td_uid_48_5804cf956cd7d.block_type = "td_block_1";
                        block_td_uid_48_5804cf956cd7d.post_count = "3";
                        block_td_uid_48_5804cf956cd7d.found_posts = "14";
                        block_td_uid_48_5804cf956cd7d.header_color = "";
                        block_td_uid_48_5804cf956cd7d.ajax_pagination_infinite_stop = "";
                        block_td_uid_48_5804cf956cd7d.max_num_pages = "5";
                        tdBlocksArray.push(block_td_uid_48_5804cf956cd7d);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>LATEST REVIEWS</span></h4>
                    </div>
                    <div id=td_uid_48_5804cf956cd7d class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_4 td_module_wrap td-animation-stack">
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                            rel=bookmark
                                            title="Why tech accelerators may soon be as irrelevant as an MBA"><img
                                                width=324 height=235 class=entry-thumb
                                                src="wp-content/uploads/2015/04/singer-324x235.jpg" alt=""
                                                title="Why tech accelerators may soon be as irrelevant as an MBA"/></a>
                                    </div>
                                    <a href="category/tagdiv-technology/tagdiv-reviews/index.html"
                                       class=td-post-category>Reviews</a></div>
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                        rel=bookmark
                                        title="Why tech accelerators may soon be as irrelevant as an MBA">Why
                                        tech accelerators may soon be as irrelevant as an MBA</a></h3>
                                <div class=td-module-meta-info>
                                    <div class=entry-review-stars><i class=td-icon-star></i><i
                                            class=td-icon-star></i><i class=td-icon-star></i><i
                                            class=td-icon-star></i><i class=td-icon-star-empty></i></div>
                                    <div class=td-module-comments><a
                                            href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html#respond">0</a>
                                    </div>
                                </div>
                                <div class=td-excerpt>
                                    The model is talking about booking her latest gig, modeling WordPress
                                    underwear in the brand latest Perfectly Fit campaign, which was shot by
                                    Lachian...
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-htc-nexus-8-with-64-bit-processor-4gb-of-ram-and-8mp-camera-leaks/index.html"
                                        rel=bookmark
                                        title="10 Upgrades under $1,000 that increase home values"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2015/04/women-100x70.jpg" alt=""
                                            title="10 Upgrades under $1,000 that increase home values"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-htc-nexus-8-with-64-bit-processor-4gb-of-ram-and-8mp-camera-leaks/index.html"
                                            rel=bookmark
                                            title="10 Upgrades under $1,000 that increase home values">10
                                            Upgrades under $1,000 that increase home values</a></h3>
                                    <div class=td-module-meta-info>
                                        <div class=entry-review-stars><i class=td-icon-star></i><i
                                                class=td-icon-star></i><i class=td-icon-star-half></i><i
                                                class=td-icon-star-empty></i><i
                                                class=td-icon-star-empty></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-intel-claims-new-ssd-750-drives-are-its-fastest-ever-for-desktop/index.html"
                                        rel=bookmark
                                        title="Intel claims new SSD 750 drives are its fastest ever for desktop"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2015/04/mixer-100x70.jpg" alt=""
                                            title="Intel claims new SSD 750 drives are its fastest ever for desktop"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-intel-claims-new-ssd-750-drives-are-its-fastest-ever-for-desktop/index.html"
                                            rel=bookmark
                                            title="Intel claims new SSD 750 drives are its fastest ever for desktop">Intel
                                            claims new SSD 750 drives are its fastest ever for...</a></h3>
                                    <div class=td-module-meta-info>
                                        <div class=entry-review-stars><i class=td-icon-star></i><i
                                                class=td-icon-star></i><i class=td-icon-star></i><i
                                                class=td-icon-star></i><i class=td-icon-star-half></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
