<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span12">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td-a-rec td-a-rec-id-custom_ad_1  "><span class=td-adspot-title>- Advertisement -</span>
                    <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/728x90.png'; ?>">
                </div>
            </div>
        </div>
    </div>
</div>
