<div class="vc_row wpb_row td-pb-row td-ss-row">
    <div class="wpb_column vc_column_container td-pb-span8">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_1 td_chuyen_sao td-pb-border-top">
                    <style scoped>
                        .td_chuyen_sao .td_module_wrap:hover .entry-title a, .td_chuyen_sao .td-subcat-item a:hover, .td_chuyen_sao .td-opacity-read .td-read-more a:hover, .td_chuyen_sao .td-opacity-author .td-post-author-name a:hover, .td_chuyen_sao .td-instagram-user a {
                            color: #f9c100
                        }

                        .td_chuyen_sao .td-next-prev-wrap a:hover, .td_chuyen_sao .td-load-more-wrap a:hover {
                            background-color: #f9c100;
                            border-color: #f9c100
                        }
                        .td_chuyen_sao .block-title span, .td_chuyen_sao .td-trending-now-title, .td_chuyen_sao .block-title a, .td_chuyen_sao .td-read-more a{
                            background-color: #f9c100
                        }

                        .td_chuyen_sao .block-title {
                            border-color: #f9c100
                        }
                    </style>
                    <div class=td-block-title-wrap>
                        <h4 class=block-title>
                            <span>CHUYỆN SAO</span>
                        </h4>
                    </div>
                    <div class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="10-landscapes-wont-even-imagined-exist/index.html"
                                                rel=bookmark
                                                title="10 Landscapes You Won’t Have Even Imagined Exist"><img
                                                    width=324 height=235 class=entry-thumb
                                                    src="wp-content/uploads/2015/03/travel-girl-324x235.jpg"
                                                    alt=""
                                                    title="10 Landscapes You Won’t Have Even Imagined Exist"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-travel/index.html"
                                           class=td-post-category>Travel</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="10-landscapes-wont-even-imagined-exist/index.html"
                                            rel=bookmark
                                            title="10 Landscapes You Won’t Have Even Imagined Exist">10
                                            Landscapes You Won’t Have Even Imagined Exist</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-03-22T05:47:34+00:00">Mar 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="10-landscapes-wont-even-imagined-exist/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Prince Edward Island, Canada
                                        Prince Edward Island is a Canadian province. It is one of the three
                                        Maritime provinces and it is the smallest in...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                            rel=bookmark
                                            title="Decorating to Celebrate the Great Outdoor Space"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/01/outside-100x70.jpg" alt=""
                                                title="Decorating to Celebrate the Great Outdoor Space"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                                rel=bookmark
                                                title="Decorating to Celebrate the Great Outdoor Space">Decorating
                                                to Celebrate the Great Outdoor Space</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-01-22T05:46:01+00:00">Jan 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                            rel=bookmark
                                            title="Zeta Architecture: Hexagon is the new circle in 2016"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/01/house-interior-100x70.jpg"
                                                alt=""
                                                title="Zeta Architecture: Hexagon is the new circle in 2016"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                                rel=bookmark
                                                title="Zeta Architecture: Hexagon is the new circle in 2016">Zeta
                                                Architecture: Hexagon is the new circle in 2016</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-01-22T05:44:07+00:00">Jan 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-what-do-i-need-to-make-it-in-business/index.html"
                                            rel=bookmark title="What Do I Need To Make It In Business?"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/bag-100x70.jpg" alt=""
                                                title="What Do I Need To Make It In Business?"/></a></div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-what-do-i-need-to-make-it-in-business/index.html"
                                                rel=bookmark title="What Do I Need To Make It In Business?">What
                                                Do I Need To Make It In Business?</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-21T06:15:43+00:00">Apr 21, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-planning-a-winter-holiday-canary-islands-offers-the-best-value-getaway-this-season/index.html"
                                            rel=bookmark
                                            title="Planning a winter holiday? Canary Islands offers"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/03/boat-100x70.jpg" alt=""
                                                title="Planning a winter holiday? Canary Islands offers"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-planning-a-winter-holiday-canary-islands-offers-the-best-value-getaway-this-season/index.html"
                                                rel=bookmark
                                                title="Planning a winter holiday? Canary Islands offers">Planning
                                                a winter holiday? Canary Islands offers</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-03-22T05:45:36+00:00">Mar 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="td_block_wrap td_block_2 td_thoi_trang td-pb-border-top">
                    <style scoped>
                        .td_thoi_trang .td_module_wrap:hover .entry-title a, .td_thoi_trang .td-subcat-item a:hover, .td_thoi_trang .td-opacity-read .td-read-more a:hover, .td_thoi_trang .td-opacity-author .td-post-author-name a:hover, .td_thoi_trang .td-instagram-user a {
                            color: #4caf50
                        }

                        .td_thoi_trang .td-next-prev-wrap a:hover, .td_thoi_trang .td-load-more-wrap a:hover {
                            background-color: #4caf50;
                            border-color: #4caf50
                        }
                        .td_thoi_trang .block-title span, .td_thoi_trang .block-title a, .td_thoi_trang .td-read-more a {
                            background-color: #4caf50
                        }

                        .td_thoi_trang .block-title {
                            border-color: #4caf50
                        }</style>
                    <div class=td-block-title-wrap>
                        <h4 class=block-title>
                            <span>THỜI TRANG</span>
                        </h4>
                    </div>
                    <div class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_2 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="whitewater-rafting-day-trip-new-york-east/index.html"
                                                rel=bookmark
                                                title="Whitewater Rafting Day Trip from New York in the East"><img
                                                    width=324 height=160 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/green-house-324x160.jpg"
                                                    alt=""
                                                    title="Whitewater Rafting Day Trip from New York in the East"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-business/index.html"
                                           class=td-post-category>Business</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="whitewater-rafting-day-trip-new-york-east/index.html"
                                            rel=bookmark
                                            title="Whitewater Rafting Day Trip from New York in the East">Whitewater
                                            Rafting Day Trip from New York in the East</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T06:23:44+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="whitewater-rafting-day-trip-new-york-east/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Whitewater Rafting Day Trip from NYC
                                        Meet at West 45th Street and 11th Avenue and board the bus for
                                        world-renowned Hunter Mountain. Many...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_2 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html"
                                                rel=bookmark
                                                title="Five things you may have missed over the weekend from the world of business"><img
                                                    width=324 height=160 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/green-324x160.jpg" alt=""
                                                    title="Five things you may have missed over the weekend from the world of business"/></a>
                                        </div>
                                        <a href="category/tagdiv-lifestyle/tagdiv-business/index.html"
                                           class=td-post-category>Business</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html"
                                            rel=bookmark
                                            title="Five things you may have missed over the weekend from the world of business">Five
                                            things you may have missed over the weekend from the...</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T06:23:43+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot...
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-express-recipes-how-to-make-creamy-papaya-raita/index.html"
                                            rel=bookmark
                                            title="Express Recipes: How to make Creamy Papaya Raita"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/green-girl-100x70.jpg" alt=""
                                                title="Express Recipes: How to make Creamy Papaya Raita"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-express-recipes-how-to-make-creamy-papaya-raita/index.html"
                                                rel=bookmark
                                                title="Express Recipes: How to make Creamy Papaya Raita">Express
                                                Recipes: How to make Creamy Papaya Raita</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T06:23:33+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html"
                                            rel=bookmark
                                            title="400k for whisky? Most expensive foods and drink auctioned"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/65-100x70.jpg" alt=""
                                                title="400k for whisky? Most expensive foods and drink auctioned"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html"
                                                rel=bookmark
                                                title="400k for whisky? Most expensive foods and drink auctioned">400k
                                                for whisky? Most expensive foods and drink auctioned</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:42+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-seeking-business-cuomo-heads-to-cuba-with-a-new-york-trade-delegation/index.html"
                                            rel=bookmark
                                            title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/66-100x70.jpg" alt=""
                                                title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-seeking-business-cuomo-heads-to-cuba-with-a-new-york-trade-delegation/index.html"
                                                rel=bookmark
                                                title="Seeking Business, Cuomo Heads to Cuba With a New York Trade Delegation">Seeking
                                                Business, Cuomo Heads to Cuba With a New York Trade...</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:42+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-food-health-star-ratings-kelloggs-reveals-the-cereal-that-gets-1-5-stars/index.html"
                                            rel=bookmark
                                            title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/64-100x70.jpg" alt=""
                                                title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-food-health-star-ratings-kelloggs-reveals-the-cereal-that-gets-1-5-stars/index.html"
                                                rel=bookmark
                                                title="Food health star ratings: Kellogg&#8217;s reveals the cereal that gets 1.5 stars">Food
                                                health star ratings: Kellogg&#8217;s reveals the cereal that
                                                gets 1.5...</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:41+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="td_block_wrap td_block_15 td_lam_dep td-pb-border-top">
                    <style>
                        .td_lam_dep .td_module_wrap:hover .entry-title a, .td_lam_dep .td-subcat-item a:hover, .td_lam_dep .td-opacity-read .td-read-more a:hover, .td_lam_dep .td-opacity-author .td-post-author-name a:hover, .td_lam_dep .td-instagram-user a {
                            color: #607d8b
                        }

                        .td_lam_dep .td-next-prev-wrap a:hover, .td_lam_dep .td-load-more-wrap a:hover {
                            background-color: #607d8b;
                            border-color: #607d8b
                        }
                        .td_lam_dep .block-title span, .td_lam_dep .block-title a, .td_lam_dep .td-read-more a {
                            background-color: #607d8b
                        }

                        .td_lam_dep .block-title {
                            border-color: #607d8b
                        }
                    </style>
                    <div class=td-block-title-wrap>
                        <h4 class=block-title><span>DU LỊCH</span></h4>
                    </div>
                    <div class="td_block_inner td-column-2">
                        <div class=td-block-row>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                                rel=bookmark
                                                title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/119-218x150.jpg" alt=""
                                                    title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-interiors/index.html"
                                           class=td-post-category>Interiors</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                            rel=bookmark
                                            title="Patricia Urquiola transparent furniture for Glas Italia with iridescent">Patricia
                                            Urquiola transparent furniture for Glas Italia with iridescent</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                                rel=bookmark
                                                title="Denton Corker Marshall the mysterious black box is biennale pavilion"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/115-218x150.jpg" alt=""
                                                    title="Denton Corker Marshall the mysterious black box is biennale pavilion"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                            rel=bookmark
                                            title="Denton Corker Marshall the mysterious black box is biennale pavilion">Denton
                                            Corker Marshall the mysterious black box is biennale pavilion</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                                rel=bookmark
                                                title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/107-218x150.jpg" alt=""
                                                    title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                            rel=bookmark
                                            title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job">Man
                                            agrees to complete $5,000 Hereford Inlet Lighthouse painting job</a>
                                    </h3>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-row>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                                rel=bookmark
                                                title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/119-218x150.jpg" alt=""
                                                    title="Patricia Urquiola transparent furniture for Glas Italia with iridescent"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-interiors/index.html"
                                           class=td-post-category>Interiors</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html"
                                            rel=bookmark
                                            title="Patricia Urquiola transparent furniture for Glas Italia with iridescent">Patricia
                                            Urquiola transparent furniture for Glas Italia with iridescent</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                                rel=bookmark
                                                title="Denton Corker Marshall the mysterious black box is biennale pavilion"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/115-218x150.jpg" alt=""
                                                    title="Denton Corker Marshall the mysterious black box is biennale pavilion"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-denton-corker-marshall-the-mysterious-black-box-is-biennale-pavilion/index.html"
                                            rel=bookmark
                                            title="Denton Corker Marshall the mysterious black box is biennale pavilion">Denton
                                            Corker Marshall the mysterious black box is biennale pavilion</a>
                                    </h3>
                                </div>
                            </div>
                            <div class=td-block-span4>
                                <div class="td_module_mx4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                                rel=bookmark
                                                title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"><img
                                                    width=218 height=150 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/107-218x150.jpg" alt=""
                                                    title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job"/></a>
                                        </div>
                                        <a href="category/tagdiv-design/tagdiv-architecture/index.html"
                                           class=td-post-category>Architecture</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-man-agrees-to-complete-50000-hereford-inlet-lighthouse-paint-job/index.html"
                                            rel=bookmark
                                            title="Man agrees to complete $5,000 Hereford Inlet Lighthouse painting job">Man
                                            agrees to complete $5,000 Hereford Inlet Lighthouse painting job</a>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="td_block_wrap td_block_1 td_suc_khoe td-pb-border-top">
                    <style>
                        .td_suc_khoe .td_module_wrap:hover .entry-title a, .td_suc_khoe .td-subcat-item a:hover, .td_suc_khoe .td-opacity-read .td-read-more a:hover, .td_suc_khoe .td-opacity-author .td-post-author-name a:hover, .td_suc_khoe .td-instagram-user a {
                            color: #f44336
                        }

                        .td_suc_khoe .td-next-prev-wrap a:hover, .td_suc_khoe .td-load-more-wrap a:hover {
                            background-color: #f44336;
                            border-color: #f44336
                        }
                        .td_suc_khoe .block-title span, .td_suc_khoe .block-title a, .td_suc_khoe .td-read-more a{
                            background-color: #f44336
                        }

                        .td_suc_khoe .block-title {
                            border-color: #f44336
                        }
                    </style>
                    <div class=td-block-title-wrap>
                        <h4 class=block-title>
                            <span>SỨC KHỎE</span>
                        </h4>
                    </div>
                    <div class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-block-span6>
                                <div class="td_module_4 td_module_wrap td-animation-stack">
                                    <div class=td-module-image>
                                        <div class=td-module-thumb><a
                                                href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html"
                                                rel=bookmark
                                                title="Amazon&#8217;s Apple Watch killer will be free and sell you everything"><img
                                                    width=324 height=235 class=entry-thumb
                                                    src="wp-content/uploads/2015/04/headphones-324x235.jpg"
                                                    alt=""
                                                    title="Amazon&#8217;s Apple Watch killer will be free and sell you everything"/></a>
                                        </div>
                                        <a href="category/tagdiv-technology/index.html"
                                           class=td-post-category>Technology</a></div>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html"
                                            rel=bookmark
                                            title="Amazon&#8217;s Apple Watch killer will be free and sell you everything">Amazon&#8217;s
                                            Apple Watch killer will be free and sell you everything</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-24T05:44:22+00:00">Apr 24, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-amazons-apple-watch-killer-will-be-free-and-sell-you-everything/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian...
                                    </div>
                                </div>
                            </div>
                            <div class=td-block-span6>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-microsoft-subsumes-open-tech-unit-back-inside-mothership/index.html"
                                            rel=bookmark
                                            title="Microsoft Subsumes Open Tech Unit Back Inside Mothership"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/tee-100x70.jpg" alt=""
                                                title="Microsoft Subsumes Open Tech Unit Back Inside Mothership"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-microsoft-subsumes-open-tech-unit-back-inside-mothership/index.html"
                                                rel=bookmark
                                                title="Microsoft Subsumes Open Tech Unit Back Inside Mothership">Microsoft
                                                Subsumes Open Tech Unit Back Inside Mothership</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-24T05:23:25+00:00">Apr 24, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                            rel=bookmark
                                            title="Why tech accelerators may soon be as irrelevant as an MBA"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/singer-100x70.jpg" alt=""
                                                title="Why tech accelerators may soon be as irrelevant as an MBA"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html"
                                                rel=bookmark
                                                title="Why tech accelerators may soon be as irrelevant as an MBA">Why
                                                tech accelerators may soon be as irrelevant as an MBA</a></h3>
                                        <div class=td-module-meta-info>
                                            <div class=entry-review-stars><i class=td-icon-star></i><i
                                                    class=td-icon-star></i><i class=td-icon-star></i><i
                                                    class=td-icon-star></i><i class=td-icon-star-empty></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-canon-xc10-4k-digital-camcorder-is-out-compact-versatile-and-for-only-2500/index.html"
                                            rel=bookmark
                                            title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/snickers-100x70.jpg" alt=""
                                                title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-canon-xc10-4k-digital-camcorder-is-out-compact-versatile-and-for-only-2500/index.html"
                                                rel=bookmark
                                                title="Canon XC10 4K Digital Camcorder Is Out: Compact and Versatile">Canon
                                                XC10 4K Digital Camcorder Is Out: Compact and Versatile</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:32+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_6 td_module_wrap td-animation-stack">
                                    <div class=td-module-thumb><a
                                            href="td-post-part-gopro-dropcam-flir-fx-camera-does-sports-a-new-camera/index.html"
                                            rel=bookmark
                                            title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera"><img
                                                width=100 height=70 class=entry-thumb
                                                src="wp-content/uploads/2015/04/43-100x70.jpg" alt=""
                                                title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera"/></a>
                                    </div>
                                    <div class=item-details>
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-part-gopro-dropcam-flir-fx-camera-does-sports-a-new-camera/index.html"
                                                rel=bookmark
                                                title="Part GoPro Dropcam: Flir FX Camera Does Sports a new camera">Part
                                                GoPro Dropcam: Flir FX Camera Does Sports a new camera</a></h3>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2015-04-22T05:23:31+00:00">Apr 22, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>

                <div class="td-a-rec td-a-rec-id-sidebar ">
                    <span class=td-adspot-title>- Advertisement -</span>
                    <div class=td-visible-desktop>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-landscape>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-portrait>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:200px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec200.jpg"
                                                                                     alt="" width=200
                                                                                     height=200/></a>
                    </div>
                    <div class=td-visible-phone>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                </div>

                <div class="td_block_wrap td_block_21 td-pb-border-top">
                    <div class=td-block-title-wrap>
                        <h4 class=block-title>
                            <span>ĐỌC NHIỀU NHẤT</span>
                        </h4>
                    </div>
                    <divclass="td_block_inner">
                        <div class="td_module_16 td_module_wrap td-animation-stack">
                            <div class="td-module-thumb"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-george-boateng-keeping-ron-vlaar-was-paul-lambert-masterstroke/" rel="bookmark" title="George Boateng: Keeping Ron Vlaar was Paul Lambert masterstroke"><img width="150" height="150" class="entry-thumb td-animation-stack-type0-2" src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/24-150x150.jpg" alt="" title="George Boateng: Keeping Ron Vlaar was Paul Lambert masterstroke"></a></div>
                            <div class="item-details">
                                <h3 class="entry-title td-module-title"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-george-boateng-keeping-ron-vlaar-was-paul-lambert-masterstroke/" rel="bookmark" title="George Boateng: Keeping Ron Vlaar was Paul Lambert masterstroke">George Boateng: Keeping Ron Vlaar was Paul Lambert masterstroke</a></h3>
                                <div class="td-module-meta-info">
                                    <a href="http://demo.tagdiv.com/newspaper_magazine/category/sport/" class="td-post-category">Sport</a> <span class="td-post-author-name"><a href="http://demo.tagdiv.com/newspaper_magazine/author/admin/">David Lee</a> <span>-</span> </span> <span class="td-post-date"><time class="entry-date updated td-module-date" datetime="2015-09-23T12:42:05+00:00">September 23, 2015</time></span> <div class="td-module-comments"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-george-boateng-keeping-ron-vlaar-was-paul-lambert-masterstroke/#respond">0</a></div> </div>
                                <div class="td-excerpt">
                                    All right. Well, take care yourself. I guess that's what you're best, presence old master? A tremor in the Force. The last time felt... </div>
                            </div>
                        </div>
                        <div class="td_module_16 td_module_wrap td-animation-stack">
                            <div class="td-module-thumb"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-gigabyte-geforce-gtx-950-review-pricing-is-everything/" rel="bookmark" title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything"><img width="150" height="150" class="entry-thumb td-animation-stack-type0-2" src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/18-150x150.jpg" alt="" title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything"></a></div>
                            <div class="item-details">
                                <h3 class="entry-title td-module-title"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-gigabyte-geforce-gtx-950-review-pricing-is-everything/" rel="bookmark" title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything">Gigabyte GeForce GTX 950 Review: Pricing Is Everything</a></h3>
                                <div class="td-module-meta-info">
                                    <a href="http://demo.tagdiv.com/newspaper_magazine/category/tech/" class="td-post-category">Tech</a> <span class="td-post-author-name"><a href="http://demo.tagdiv.com/newspaper_magazine/author/admin/">David Lee</a> <span>-</span> </span> <span class="td-post-date"><time class="entry-date updated td-module-date" datetime="2015-09-24T12:41:52+00:00">September 24, 2015</time></span> <div class="td-module-comments"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-gigabyte-geforce-gtx-950-review-pricing-is-everything/#respond">0</a></div> </div>
                                <div class="td-excerpt">
                                    All right. Well, take care yourself. I guess that's what you're best, presence old master? A tremor in the Force. The last time felt... </div>
                            </div>
                        </div>
                        <div class="td_module_16 td_module_wrap td-animation-stack">
                            <div class="td-module-thumb"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-fashion-week-parties-night-4/" rel="bookmark" title="Fashion Week Parties: Night 4"><img width="150" height="150" class="entry-thumb td-animation-stack-type0-2" src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/9-150x150.jpg" alt="" title="Fashion Week Parties: Night 4"></a></div>
                            <div class="item-details">
                                <h3 class="entry-title td-module-title"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-fashion-week-parties-night-4/" rel="bookmark" title="Fashion Week Parties: Night 4">Fashion Week Parties: Night 4</a></h3>
                                <div class="td-module-meta-info">
                                    <a href="http://demo.tagdiv.com/newspaper_magazine/category/fashion/" class="td-post-category">Fashion</a> <span class="td-post-author-name"><a href="http://demo.tagdiv.com/newspaper_magazine/author/admin/">David Lee</a> <span>-</span> </span> <span class="td-post-date"><time class="entry-date updated td-module-date" datetime="2015-09-23T12:41:34+00:00">September 23, 2015</time></span> <div class="td-module-comments"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-fashion-week-parties-night-4/#respond">0</a></div> </div>
                                <div class="td-excerpt">
                                    All right. Well, take care yourself. I guess that's what you're best, presence old master? A tremor in the Force. The last time felt... </div>
                            </div>
                        </div>
                        <div class="td_module_16 td_module_wrap td-animation-stack">
                            <div class="td-module-thumb"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-celebrity-make-up-artist-gary-cockerill-shows-you-beauty-trick/" rel="bookmark" title="Celebrity make-up artist Gary Cockerill shows you beauty trick"><img width="150" height="150" class="entry-thumb td-animation-stack-type0-2" src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/15-150x150.jpg" alt="" title="Celebrity make-up artist Gary Cockerill shows you beauty trick"></a></div>
                            <div class="item-details">
                                <h3 class="entry-title td-module-title"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-celebrity-make-up-artist-gary-cockerill-shows-you-beauty-trick/" rel="bookmark" title="Celebrity make-up artist Gary Cockerill shows you beauty trick">Celebrity make-up artist Gary Cockerill shows you beauty trick</a></h3>
                                <div class="td-module-meta-info">
                                    <a href="http://demo.tagdiv.com/newspaper_magazine/category/photography/" class="td-post-category">Photography</a> <span class="td-post-author-name"><a href="http://demo.tagdiv.com/newspaper_magazine/author/admin/">David Lee</a> <span>-</span> </span> <span class="td-post-date"><time class="entry-date updated td-module-date" datetime="2015-09-24T14:41:46+00:00">September 24, 2015</time></span> <div class="td-module-comments"><a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-celebrity-make-up-artist-gary-cockerill-shows-you-beauty-trick/#respond">0</a></div> </div>
                                <div class="td-excerpt">
                                    All right. Well, take care yourself. I guess that's what you're best, presence old master? A tremor in the Force. The last time felt... </div>
                            </div>
                        </div>
                    </div>


            <div class="td_block_wrap td_block_15 td-pb-border-top">
                <div class=td-block-title-wrap>
                    <h4 class=block-title>
                        <span>MỚI NHẤT</span>
                    </h4>
                </div>
                <div class="td_block_inner td-column-1">
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-rosie-huntington-whiteley-talks-beauty-habits-career-ambitions-and-going-nude-for-art/index.html"
                                        rel=bookmark
                                        title="Rosie Huntington Whiteley Talks Beauty Habits Career Art"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/108-218x150.jpg" alt=""
                                            title="Rosie Huntington Whiteley Talks Beauty Habits Career Art"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-rosie-huntington-whiteley-talks-beauty-habits-career-ambitions-and-going-nude-for-art/index.html"
                                    rel=bookmark
                                    title="Rosie Huntington Whiteley Talks Beauty Habits Career Art">Rosie
                                    Huntington Whiteley Talks Beauty Habits Career Art</a></h3>
                        </div>
                    </div>
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-bayside-ranch-a-perfect-canvas-for-interior-designer-2016/index.html"
                                        rel=bookmark
                                        title="Bayside Ranch a perfect canvas for interior designer 2016"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/109-218x150.jpg" alt=""
                                            title="Bayside Ranch a perfect canvas for interior designer 2016"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-bayside-ranch-a-perfect-canvas-for-interior-designer-2016/index.html"
                                    rel=bookmark
                                    title="Bayside Ranch a perfect canvas for interior designer 2016">Bayside
                                    Ranch a perfect canvas for interior designer 2016</a></h3>
                        </div>
                    </div>
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                        rel=bookmark
                                        title="2016 Decorators opens with home design inspiration"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/house-218x150.jpg" alt=""
                                            title="2016 Decorators opens with home design inspiration"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                    rel=bookmark
                                    title="2016 Decorators opens with home design inspiration">2016
                                    Decorators opens with home design inspiration</a></h3>
                        </div>
                    </div>
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                        rel=bookmark
                                        title="Artist brings air of distinction to Delafield apartment"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/110-218x150.jpg" alt=""
                                            title="Artist brings air of distinction to Delafield apartment"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                    rel=bookmark
                                    title="Artist brings air of distinction to Delafield apartment">Artist
                                    brings air of distinction to Delafield apartment</a></h3>
                        </div>
                    </div>
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                        rel=bookmark
                                        title="2016 Decorators opens with home design inspiration"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/house-218x150.jpg" alt=""
                                            title="2016 Decorators opens with home design inspiration"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-2015-decorators-opens-with-home-design-inspiration-benefiting-symphony-orchestra/index.html"
                                    rel=bookmark
                                    title="2016 Decorators opens with home design inspiration">2016
                                    Decorators opens with home design inspiration</a></h3>
                        </div>
                    </div>
                    <div class=td-block-span12>
                        <div class="td_module_mx4 td_module_wrap td-animation-stack">
                            <div class=td-module-image>
                                <div class=td-module-thumb><a
                                        href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                        rel=bookmark
                                        title="Artist brings air of distinction to Delafield apartment"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/110-218x150.jpg" alt=""
                                            title="Artist brings air of distinction to Delafield apartment"/></a>
                                </div>
                                <a href="category/tagdiv-design/tagdiv-make-it-modern/index.html"
                                   class=td-post-category>Make it modern</a></div>
                            <h3 class="entry-title td-module-title"><a
                                    href="td-post-artist-brings-air-of-distinction-to-delafield-apartment/index.html"
                                    rel=bookmark
                                    title="Artist brings air of distinction to Delafield apartment">Artist
                                    brings air of distinction to Delafield apartment</a></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
