<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span8">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_11 td-pb-border-top">
                    <div class=td-block-title-wrap>
                        <h4 class=block-title>
                            <span>LÀM ĐẸP</span>
                        </h4>
                    </div>
                    <div class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html"
                                        rel=bookmark
                                        title="Aston Villa beat Liverpool team to join in the FA Cup final"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/snowboard-218x150.jpg" alt=""
                                            title="Aston Villa beat Liverpool team to join in the FA Cup final"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html"
                                            rel=bookmark
                                            title="Aston Villa beat Liverpool team to join in the FA Cup final">Aston
                                            Villa beat Liverpool team to join in the FA Cup final</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:55+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Calvin Klein known for launching the careers of such svelte models
                                        as Brooke Shields and Kate Moss to cast a model who deviates from
                                        the...
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html"
                                        rel=bookmark
                                        title="Home Run Kitten Favored in Competitive San Simeon"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/gym-girl-218x150.jpg" alt=""
                                            title="Home Run Kitten Favored in Competitive San Simeon"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html"
                                            rel=bookmark
                                            title="Home Run Kitten Favored in Competitive San Simeon">Home
                                            Run Kitten Favored in Competitive San Simeon</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:54+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html"
                                        rel=bookmark
                                        title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/boat-red-218x150.jpg" alt=""
                                            title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html"
                                            rel=bookmark
                                            title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game">Blake
                                            Griffin posterizes Aron Baynes twice in Clippers-Spurs Game</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:54+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html"
                                        rel=bookmark
                                        title="John Isner, lonely standard-bearer of US men&#8217;s tennis"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/biker-218x150.jpg" alt=""
                                            title="John Isner, lonely standard-bearer of US men&#8217;s tennis"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html"
                                            rel=bookmark
                                            title="John Isner, lonely standard-bearer of US men&#8217;s tennis">John
                                            Isner, lonely standard-bearer of US men&#8217;s tennis</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:53+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html"
                                        rel=bookmark
                                        title="South Korean Horse Racing Expands Broadcasts Abroad"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/85-218x150.jpg" alt=""
                                            title="South Korean Horse Racing Expands Broadcasts Abroad"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html"
                                            rel=bookmark
                                            title="South Korean Horse Racing Expands Broadcasts Abroad">South
                                            Korean Horse Racing Expands Broadcasts Abroad</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:53+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td-a-rec td-a-rec-id-sidebar  ">
                    <span class=td-adspot-title>- Advertisement -</span>
                    <div class=td-visible-desktop>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-landscape>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-portrait>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:200px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec200.jpg"
                                                                                     alt="" width=200
                                                                                     height=200/></a>
                    </div>
                    <div class=td-visible-phone>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
