<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span12">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_trending_now td_uid_16_5804cf95556c9_rand td-pb-border-top"
                     data-td-block-uid=td_uid_16_5804cf95556c9>
                    <script>var block_td_uid_16_5804cf95556c9 = new tdBlock();
                        block_td_uid_16_5804cf95556c9.id = "td_uid_16_5804cf95556c9";
                        block_td_uid_16_5804cf95556c9.atts = '{"limit":5,"sort":"random_posts","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"","category_ids":"","custom_title":"","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":3,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_16_5804cf95556c9_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_16_5804cf95556c9.td_column_number = "3";
                        block_td_uid_16_5804cf95556c9.block_type = "td_block_trending_now";
                        block_td_uid_16_5804cf95556c9.post_count = "5";
                        block_td_uid_16_5804cf95556c9.found_posts = "161";
                        block_td_uid_16_5804cf95556c9.header_color = "";
                        block_td_uid_16_5804cf95556c9.ajax_pagination_infinite_stop = "";
                        block_td_uid_16_5804cf95556c9.max_num_pages = "33";
                        tdBlocksArray.push(block_td_uid_16_5804cf95556c9);</script>
                    <div id=td_uid_16_5804cf95556c9 class=td_block_inner>
                        <div class=td-block-row>
                            <div class=td-trending-now-wrapper id=td_uid_16_5804cf95556c9 data-start="">
                                <div class=td-trending-now-title>Trending Now</div>
                                <div class=td-trending-now-display-area>
                                    <div class="td_module_trending_now td-trending-now-post-0 td-trending-now-post">
                                        <h3 class="entry-title td-module-title"><a
                                                href="furniture-for-glass-italia-with-an-iridescent-gold/index.html"
                                                rel=bookmark
                                                title="Furniture for Glass Italia with an iridescent gold">Furniture
                                                for Glass Italia with an iridescent gold</a></h3>
                                    </div>
                                    <div class="td_module_trending_now td-trending-now-post-1 td-trending-now-post">
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html"
                                                rel=bookmark
                                                title="400k for whisky? Most expensive foods and drink auctioned">400k
                                                for whisky? Most expensive foods and drink auctioned</a></h3>
                                    </div>
                                    <div class="td_module_trending_now td-trending-now-post-2 td-trending-now-post">
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-chilled-pea-soup-with-fried-ham-croquettes-recipe/index.html"
                                                rel=bookmark
                                                title="Chilled pea soup with fried ham croquettes recipe">Chilled
                                                pea soup with fried ham croquettes recipe</a></h3>
                                    </div>
                                    <div class="td_module_trending_now td-trending-now-post-3 td-trending-now-post">
                                        <h3 class="entry-title td-module-title"><a
                                                href="td-post-if-you-only-knew-how-much-your-relative-churn-rate-matters/index.html"
                                                rel=bookmark
                                                title="If You Only Knew How Much Your Relative Churn Rate Matters">If
                                                You Only Knew How Much Your Relative Churn Rate Matters</a></h3>
                                    </div>
                                    <div class="td_module_trending_now td-trending-now-post-4 td-trending-now-post">
                                        <h3 class="entry-title td-module-title"><a
                                                href="kitchen-decorating-furnish-and-accessorize-with-fun/index.html"
                                                rel=bookmark
                                                title="Kitchen decorating Furnish and accessorize with fun">Kitchen
                                                decorating Furnish and accessorize with fun</a></h3>
                                    </div>
                                </div>
                                <div class=td-next-prev-wrap><a href="#"
                                                                class="td_ajax-prev-pagex td-trending-now-nav-left"
                                                                data-block-id=td_uid_16_5804cf95556c9
                                                                data-moving=left data-control-start=""><i
                                            class=td-icon-menu-left></i></a><a href="#"
                                                                               class="td_ajax-next-pagex td-trending-now-nav-right"
                                                                               data-block-id=td_uid_16_5804cf95556c9
                                                                               data-moving=right
                                                                               data-control-start=""><i
                                            class=td-icon-menu-right></i></a></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="td_block_wrap td_block_big_grid_3 td_uid_17_5804cf9557134_rand td-grid-style-1 td-hover-1 td-pb-border-top"
                     data-td-block-uid=td_uid_17_5804cf9557134>
                    <div id=td_uid_17_5804cf9557134 class=td_block_inner>
                        <div class=td-big-grid-wrapper>
                            <div class="td_module_mx5 td-animation-stack td-big-grid-post-0 td-big-grid-post td-big-thumb">
                                <div class=td-module-thumb><a
                                        href="wordpress-news-magazine-charts-the-most-fashionable-new-york-couples-in-2016/index.html"
                                        rel=bookmark
                                        title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016"><img
                                            width=534 height=462 class=entry-thumb
                                            src="wp-content/uploads/2016/01/couple-534x462.jpg" alt=""
                                            title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016"/></a>
                                </div>
                                <div class=td-meta-info-container>
                                    <div class=td-meta-align>
                                        <div class=td-big-grid-meta>
                                            <a href="category/tagdiv-lifestyle/tagdiv-health-fitness/index.html"
                                               class=td-post-category>Health &amp; Fitness</a>
                                            <h3 class="entry-title td-module-title"><a
                                                    href="wordpress-news-magazine-charts-the-most-fashionable-new-york-couples-in-2016/index.html"
                                                    rel=bookmark
                                                    title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016">WordPress
                                                    News Magazine Charts the Most Fashionable New York Couples
                                                    in 2016</a></h3></div>
                                        <div class=td-module-meta-info>
                                                <span class=td-post-author-name><a
                                                        href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                                <span class=td-post-date><time
                                                        class="entry-date updated td-module-date"
                                                        datetime="2016-01-22T05:58:41+00:00">Jan 22, 2016</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class=td-big-grid-scroll>
                                <div class="td_module_mx11 td-animation-stack td-big-grid-post-1 td-big-grid-post td-medium-thumb">
                                    <div class=td-module-thumb><a
                                            href="the-most-anticipated-charter-flights-in-the-canary-islands/index.html"
                                            rel=bookmark
                                            title="The Most Anticipated Charter Flights in the Canary Islands"><img
                                                width=533 height=261 class=entry-thumb
                                                src="wp-content/uploads/2015/02/plane-533x261.jpg" alt=""
                                                title="The Most Anticipated Charter Flights in the Canary Islands"/></a>
                                    </div>
                                    <div class=td-meta-info-container>
                                        <div class=td-meta-align>
                                            <div class=td-big-grid-meta>
                                                <a href="category/tagdiv-lifestyle/tagdiv-travel/index.html"
                                                   class=td-post-category>Travel</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="the-most-anticipated-charter-flights-in-the-canary-islands/index.html"
                                                        rel=bookmark
                                                        title="The Most Anticipated Charter Flights in the Canary Islands">The
                                                        Most Anticipated Charter Flights in the Canary
                                                        Islands</a></h3></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-2 td-big-grid-post td-small-thumb">
                                    <div class=td-module-thumb><a
                                            href="15-grooming-techniques-every-man-needs-to-know/index.html"
                                            rel=bookmark
                                            title="15 Grooming Techniques Every Man Needs to Know"><img
                                                width=265 height=198 class=entry-thumb
                                                src="wp-content/uploads/2015/02/bike-265x198.jpg" alt=""
                                                title="15 Grooming Techniques Every Man Needs to Know"/></a>
                                    </div>
                                    <div class=td-meta-info-container>
                                        <div class=td-meta-align>
                                            <div class=td-big-grid-meta>
                                                <a href="category/tagdiv-music/index.html"
                                                   class=td-post-category>Music</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="15-grooming-techniques-every-man-needs-to-know/index.html"
                                                        rel=bookmark
                                                        title="15 Grooming Techniques Every Man Needs to Know">15
                                                        Grooming Techniques Every Man Needs to Know</a></h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-3 td-big-grid-post td-small-thumb">
                                    <div class=td-module-thumb><a
                                            href="fashion-photography-helps-raising-funds/index.html"
                                            rel=bookmark
                                            title="Fashion Photography Helps Raising Funds"><img width=265
                                                                                                 height=198
                                                                                                 class=entry-thumb
                                                                                                 src="wp-content/uploads/2015/02/girl-265x198.jpg"
                                                                                                 alt=""
                                                                                                 title="Fashion Photography Helps Raising Funds"/></a>
                                    </div>
                                    <div class=td-meta-info-container>
                                        <div class=td-meta-align>
                                            <div class=td-big-grid-meta>
                                                <a href="category/tagdiv-fashion/tagdiv-style-hunter/index.html"
                                                   class=td-post-category>Style hunter</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="fashion-photography-helps-raising-funds/index.html"
                                                        rel=bookmark
                                                        title="Fashion Photography Helps Raising Funds">Fashion
                                                        Photography Helps Raising Funds</a></h3></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=clearfix></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
