<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span12">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_big_grid_1 td-grid-style-1 td-hover-1 td-pb-border-top">
                    <div class="td_block_inner">
                        <div class="td-big-grid-wrapper">
                            <div class="td_module_mx5 td-animation-stack td-big-grid-post-0 td-big-grid-post td-big-thumb">
                                <div class="td-module-thumb">
                                    <a href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-celebrity-make-up-artist-gary-cockerill-shows-you-beauty-trick/"
                                        rel="bookmark"
                                        title="Celebrity make-up artist Gary Cockerill shows you beauty trick"><img
                                            width="534" height="462" class="entry-thumb td-animation-stack-type0-2"
                                            src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/15-534x462.jpg"
                                            alt=""
                                            title="Celebrity make-up artist Gary Cockerill shows you beauty trick"></a>
                                </div>
                                <div class="td-meta-info-container">
                                    <div class="td-meta-align">
                                        <div class="td-big-grid-meta">
                                            <a href="http://demo.tagdiv.com/newspaper_magazine/category/photography/"
                                               class="td-post-category">Photography</a>
                                            <h3 class="entry-title td-module-title"><a
                                                    href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-celebrity-make-up-artist-gary-cockerill-shows-you-beauty-trick/"
                                                    rel="bookmark"
                                                    title="Celebrity make-up artist Gary Cockerill shows you beauty trick">Celebrity
                                                    make-up artist Gary Cockerill shows you beauty trick</a></h3></div>
                                        <div class="td-module-meta-info">
                                            <span class="td-post-author-name"><a
                                                    href="http://demo.tagdiv.com/newspaper_magazine/author/admin/">David Lee</a> <span>-</span> </span>
                                            <span class="td-post-date"><time class="entry-date updated td-module-date"
                                                                             datetime="2015-09-24T14:41:46+00:00">September 24, 2015</time></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="td-big-grid-scroll">
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-1 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb">
                                        <a
                                            href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-the-workout-that-burns-more-calories-than-running/"
                                            rel="bookmark"
                                            title="The Workout That Burns More Calories Than Running"><img width="265"
                                                                                                           height="198"
                                                                                                           class="entry-thumb td-animation-stack-type0-2"
                                                                                                           src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/61-265x198.jpg"
                                                                                                           alt=""
                                                                                                           title="The Workout That Burns More Calories Than Running"></a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="http://demo.tagdiv.com/newspaper_magazine/category/lifestyle/health/"
                                                   class="td-post-category">Health</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-the-workout-that-burns-more-calories-than-running/"
                                                        rel="bookmark"
                                                        title="The Workout That Burns More Calories Than Running">The
                                                        Workout That Burns More Calories Than Running</a></h3></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-2 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb"><a
                                            href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-gigabyte-geforce-gtx-950-review-pricing-is-everything/"
                                            rel="bookmark"
                                            title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything"><img
                                                width="265" height="198" class="entry-thumb td-animation-stack-type0-2"
                                                src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/18-265x198.jpg"
                                                alt=""
                                                title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything"></a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="http://demo.tagdiv.com/newspaper_magazine/category/tech/"
                                                   class="td-post-category">Tech</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="http://demo.tagdiv.com/newspaper_magazine/2015/09/24/td-post-gigabyte-geforce-gtx-950-review-pricing-is-everything/"
                                                        rel="bookmark"
                                                        title="Gigabyte GeForce GTX 950 Review: Pricing Is Everything">Gigabyte
                                                        GeForce GTX 950 Review: Pricing Is Everything</a></h3></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-3 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb"><a
                                            href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-a-thomas-hart-benton-mural-repurposed-as-a-writing-desk/"
                                            rel="bookmark"
                                            title="A Thomas Hart Benton Mural, Repurposed as a Writing Desk"><img
                                                width="265" height="198" class="entry-thumb td-animation-stack-type0-2"
                                                src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/54-265x198.jpg"
                                                alt="" title="A Thomas Hart Benton Mural, Repurposed as a Writing Desk"></a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="http://demo.tagdiv.com/newspaper_magazine/category/lifestyle/arts/"
                                                   class="td-post-category">Arts</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-a-thomas-hart-benton-mural-repurposed-as-a-writing-desk/"
                                                        rel="bookmark"
                                                        title="A Thomas Hart Benton Mural, Repurposed as a Writing Desk">A
                                                        Thomas Hart Benton Mural, Repurposed as a Writing Desk</a></h3>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="td_module_mx6 td-animation-stack td-big-grid-post-4 td-big-grid-post td-small-thumb">
                                    <div class="td-module-thumb"><a
                                            href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-fashion-week-parties-night-4/"
                                            rel="bookmark" title="Fashion Week Parties: Night 4"><img width="265"
                                                                                                      height="198"
                                                                                                      class="entry-thumb td-animation-stack-type0-2"
                                                                                                      src="http://demo.tagdiv.com/newspaper_magazine/wp-content/uploads/2015/09/9-265x198.jpg"
                                                                                                      alt=""
                                                                                                      title="Fashion Week Parties: Night 4"></a>
                                    </div>
                                    <div class="td-meta-info-container">
                                        <div class="td-meta-align">
                                            <div class="td-big-grid-meta">
                                                <a href="http://demo.tagdiv.com/newspaper_magazine/category/fashion/"
                                                   class="td-post-category">Fashion</a>
                                                <h3 class="entry-title td-module-title"><a
                                                        href="http://demo.tagdiv.com/newspaper_magazine/2015/09/23/td-post-fashion-week-parties-night-4/"
                                                        rel="bookmark" title="Fashion Week Parties: Night 4">Fashion
                                                        Week Parties: Night 4</a></h3></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
