<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_19 td_me_be td-pb-border-top">
                    <style scoped>
                        .td_me_be .td_module_wrap:hover .entry-title a, .td_me_be .td-subcat-item a:hover, .td_me_be .td-opacity-read .td-read-more a:hover, .td_me_be .td-opacity-author .td-post-author-name a:hover, .td_me_be .td-instagram-user a {
                            color: rgb(158, 9, 140);
                        }

                        .td_me_be .td-next-prev-wrap a:hover, .td_me_be .td-load-more-wrap a:hover {
                            background-color: rgb(158, 9, 140);
                            border-color: rgb(158, 9, 140);
                        }
                        .td_me_be .block-title span, .td_me_be .block-title a, .td_me_be .td-read-more a{
                            background-color: rgb(158, 9, 140);
                        }

                        .td_me_be .block-title {
                            border-color: rgb(158, 9, 140);
                        }
                    </style>
                    <div class=td-block-title-wrap>
                        <a title"Mẹ và bé" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_ME_VA_BE]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_ME_VA_BE]['cate_id']]) ?>">
                            <h4 class=block-title>
                                <span><i class="fa <?php echo $this->arrCategory[\My\General::CATEGORY_ME_VA_BE]['cate_icon'] ?>"></i> MẸ VÀ BÉ</span>
                            </h4>
                        </a>
                    </div>
                    <div class="td_block_inner td-column-1">
                        <div class="td_module_mx1 td_module_wrap td-animation-stack">
                            <div class=td-module-thumb>
                                <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_id']]) ?>"
                                    rel=bookmark
                                    title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_title'] ?>">
                                    <img width=356 height=220 class=entry-thumb
                                        src="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_main_image'] ?>"
                                         alt="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_title'] ?>"
                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_title'] ?>"/>
                                </a>
                            </div>
                            <div class=td-module-meta-info>
                                <h3 class="entry-title td-module-title">
                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_id']]) ?>"
                                        rel=bookmark
                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_title'] ?>">
                                        <?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['cont_title'] ?>
                                    </a>
                                </h3>
                                <div class=td-editor-date>
                                    <span class=td-author-date>
                                        <span class=td-post-date>
                                                <?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_ME_VA_BE][0]['created_date']); ?>
                                            </time>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <?php for($i=1; $i<=3; $i++) { ?>
                        <div class="td_module_mx2 td_module_wrap td-animation-stack">
                            <div class=td-module-thumb>
                                <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_id']]) ?>"
                                    rel=bookmark
                                    title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_title'] ?>">
                                    <img width=80 height=60 class=entry-thumb
                                        src="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_resize_image'] ?>"
                                         alt="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_title'] ?>"
                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_title'] ?>"/></a>
                            </div>
                            <div class=item-details>
                                <h3 class="entry-title td-module-title">
                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_id']]) ?>"
                                        rel=bookmark
                                        title="<?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_title'] ?>">
                                        <?php echo $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['cont_title'] ?>
                                    </a>
                                </h3>
                                <div class=td-module-meta-info>
                                        <span class=td-post-date>
                                            <time class="entry-date updated td-module-date"
                                                       datetime="<?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['created_date']); ?>">
                                                <?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_ME_VA_BE][$i]['created_date']); ?>
                                            </time>
                                        </span>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_19 td_mon_ngon td-pb-border-top">
                    <style scoped>
                        .td_mon_ngon .td_module_wrap:hover .entry-title a, .td_mon_ngon .td-subcat-item a:hover, .td_mon_ngon .td-opacity-read .td-read-more a:hover, .td_mon_ngon .td-opacity-author .td-post-author-name a:hover, .td_mon_ngon .td-instagram-user a {
                            color: #4db2ec;
                        }

                        .td_mon_ngon .td-next-prev-wrap a:hover, .td_mon_ngon .td-load-more-wrap a:hover {
                            background-color: #4db2ec;
                            border-color: #4db2ec;
                        }
                        .td_mon_ngon .block-title span, .td_mon_ngon .block-title a, .td_mon_ngon .td-read-more a{
                            background-color: #4db2ec
                        }

                        .td_mon_ngon .block-title {
                            border-color: #4db2ec
                        }
                    </style>
                    <div class=td-block-title-wrap>
                        <a title="Món ngon" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategory[\My\General::CATEGORY_MON_NGON]['cate_slug'], 'cateId' => $this->arrCategory[\My\General::CATEGORY_MON_NGON]['cate_id']]) ?>">
                            <h4 class=block-title>
                                <span><i class="fa <?php echo $this->arrCategory[\My\General::CATEGORY_MON_NGON]['cate_icon'] ?>"></i> MÓN NGON</span>
                            </h4>
                        </a>
                    </div>
                    <div class="td_block_inner td-column-1">
                        <div class="td_module_mx1 td_module_wrap td-animation-stack">
                            <div class=td-module-thumb>
                                <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_id']]) ?>"
                                   rel=bookmark
                                   title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_title'] ?>">
                                    <img width=356 height=220 class=entry-thumb
                                         src="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_main_image'] ?>"
                                         alt="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_title'] ?>"
                                         title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_title'] ?>"/>
                                </a>
                            </div>
                            <div class=td-module-meta-info>
                                <h3 class="entry-title td-module-title">
                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_id']]) ?>"
                                       rel=bookmark
                                       title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_title'] ?>">
                                        <?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['cont_title'] ?>
                                    </a>
                                </h3>
                                <div class=td-editor-date>
                                    <span class=td-author-date>
                                        <span class=td-post-date>
                                                <?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_MON_NGON][0]['created_date']); ?>
                                            </time>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <?php for($i=1; $i<=3; $i++) { ?>
                            <div class="td_module_mx2 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb>
                                    <a rel="nofollow" href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_id']]) ?>"
                                       rel=bookmark
                                       title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_title'] ?>">
                                        <img width=80 height=60 class=entry-thumb
                                             src="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_resize_image'] ?>"
                                             alt="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_title'] ?>"
                                             title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_title'] ?>"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title">
                                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_slug'], 'contentId' => $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_id']]) ?>"
                                           rel=bookmark
                                           title="<?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_title'] ?>">
                                            <?php echo $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['cont_title'] ?>
                                        </a>
                                    </h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-date>
                                            <time class="entry-date updated td-module-date"
                                                  datetime="<?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['created_date']); ?>">
                                                <?php echo date('d-m-Y', $this->arrContent[\My\General::CATEGORY_MON_NGON][$i]['created_date']); ?>
                                            </time>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <aside class="widget widget_categories">
                <div class="block-title">
                    <span>CATEGORIES</span>
                </div>
                <ul>
                    <?php foreach ($this->arrCategory as $category) { ?>
                    <li class="cat-item">
                        <a href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $category['cate_slug'], 'cateId' => $category['cate_id']]) ?>">
                            <i class="fa <?php echo $category['cate_icon'] ?>"></i>  <?php echo $category['cate_name'] ?>
                        </a>
                        <span class="td-cat-no"><?php echo $category['total_content'] ?></span>
                    </li>
                <?php } ?>
                </ul>
            </aside>
        </div>
    </div>
</div>
