<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span8">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td_block_wrap td_block_11 td_uid_49_5804cf956f359_rand td-pb-border-top"
                     data-td-block-uid=td_uid_49_5804cf956f359>
                    <script>var block_td_uid_49_5804cf956f359 = new tdBlock();
                        block_td_uid_49_5804cf956f359.id = "td_uid_49_5804cf956f359";
                        block_td_uid_49_5804cf956f359.atts = '{"limit":5,"sort":"","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"23","category_ids":"","custom_title":"PERFORMANCE TRAINING","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":2,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_49_5804cf956f359_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_49_5804cf956f359.td_column_number = "2";
                        block_td_uid_49_5804cf956f359.block_type = "td_block_11";
                        block_td_uid_49_5804cf956f359.post_count = "5";
                        block_td_uid_49_5804cf956f359.found_posts = "11";
                        block_td_uid_49_5804cf956f359.header_color = "";
                        block_td_uid_49_5804cf956f359.ajax_pagination_infinite_stop = "";
                        block_td_uid_49_5804cf956f359.max_num_pages = "3";
                        tdBlocksArray.push(block_td_uid_49_5804cf956f359);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>PERFORMANCE TRAINING</span>
                        </h4></div>
                    <div id=td_uid_49_5804cf956f359 class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html"
                                        rel=bookmark
                                        title="Aston Villa beat Liverpool team to join in the FA Cup final"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/snowboard-218x150.jpg" alt=""
                                            title="Aston Villa beat Liverpool team to join in the FA Cup final"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html"
                                            rel=bookmark
                                            title="Aston Villa beat Liverpool team to join in the FA Cup final">Aston
                                            Villa beat Liverpool team to join in the FA Cup final</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius/index.html">John Doe</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:55+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        Calvin Klein known for launching the careers of such svelte models
                                        as Brooke Shields and Kate Moss to cast a model who deviates from
                                        the...
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html"
                                        rel=bookmark
                                        title="Home Run Kitten Favored in Competitive San Simeon"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/gym-girl-218x150.jpg" alt=""
                                            title="Home Run Kitten Favored in Competitive San Simeon"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html"
                                            rel=bookmark
                                            title="Home Run Kitten Favored in Competitive San Simeon">Home
                                            Run Kitten Favored in Competitive San Simeon</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:54+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-home-run-kitten-favored-in-competitive-san-simeon/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html"
                                        rel=bookmark
                                        title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/boat-red-218x150.jpg" alt=""
                                            title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html"
                                            rel=bookmark
                                            title="Blake Griffin posterizes Aron Baynes twice in Clippers-Spurs Game">Blake
                                            Griffin posterizes Aron Baynes twice in Clippers-Spurs Game</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:54+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-blake-griffin-posterizes-aron-baynes-twice-in-clippers-spurs-game/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html"
                                        rel=bookmark
                                        title="John Isner, lonely standard-bearer of US men&#8217;s tennis"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/biker-218x150.jpg" alt=""
                                            title="John Isner, lonely standard-bearer of US men&#8217;s tennis"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html"
                                            rel=bookmark
                                            title="John Isner, lonely standard-bearer of US men&#8217;s tennis">John
                                            Isner, lonely standard-bearer of US men&#8217;s tennis</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:53+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-john-isner-lonely-standard-bearer-of-us-mens-tennis/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_10 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html"
                                        rel=bookmark
                                        title="South Korean Horse Racing Expands Broadcasts Abroad"><img
                                            width=218 height=150 class=entry-thumb
                                            src="wp-content/uploads/2015/04/85-218x150.jpg" alt=""
                                            title="South Korean Horse Racing Expands Broadcasts Abroad"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html"
                                            rel=bookmark
                                            title="South Korean Horse Racing Expands Broadcasts Abroad">South
                                            Korean Horse Racing Expands Broadcasts Abroad</a></h3>
                                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a href="author/marius2/index.html">Matt Cloey</a> <span>-</span> </span>
                                            <span class=td-post-date><time
                                                    class="entry-date updated td-module-date"
                                                    datetime="2015-04-22T05:23:53+00:00">Apr 22, 2015</time></span>
                                        <div class=td-module-comments><a
                                                href="td-post-south-korean-horse-racing-expands-broadcasts-abroad/index.html#respond">0</a>
                                        </div>
                                    </div>
                                    <div class=td-excerpt>
                                        The model is talking about booking her latest gig, modeling
                                        WordPress underwear in the brand latest Perfectly Fit campaign,
                                        which was shot by Lachian Bailey....
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wpb_column vc_column_container td-pb-span4">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td-a-rec td-a-rec-id-sidebar  "><span
                        class=td-adspot-title>- Advertisement -</span>
                    <div class=td-visible-desktop>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-landscape>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                    <div class=td-visible-tablet-portrait>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:200px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec200.jpg"
                                                                                     alt="" width=200
                                                                                     height=200/></a>
                    </div>
                    <div class=td-visible-phone>
                        <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                                     style=max-width:300px
                                                                                     src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                                     alt="" width=300
                                                                                     height=250/></a>
                    </div>
                </div>
                <div class="td_block_wrap td_block_6 td_uid_51_5804cf9573edb_rand td-pb-border-top"
                     data-td-block-uid=td_uid_51_5804cf9573edb>
                    <style scoped>.td_uid_51_5804cf9573edb_rand .td_module_wrap:hover .entry-title a, .td_uid_51_5804cf9573edb_rand a.td-pulldown-filter-link:hover, .td_uid_51_5804cf9573edb_rand .td-subcat-item a:hover, .td_uid_51_5804cf9573edb_rand .td-subcat-item .td-cur-simple-item, .td_uid_51_5804cf9573edb_rand .td_quote_on_blocks, .td_uid_51_5804cf9573edb_rand .td-opacity-cat .td-post-category:hover, .td_uid_51_5804cf9573edb_rand .td-opacity-read .td-read-more a:hover, .td_uid_51_5804cf9573edb_rand .td-opacity-author .td-post-author-name a:hover, .td_uid_51_5804cf9573edb_rand .td-instagram-user a {
                            color: #ff7500
                        }

                        .td_uid_51_5804cf9573edb_rand .td-next-prev-wrap a:hover, .td_uid_51_5804cf9573edb_rand .td-load-more-wrap a:hover {
                            background-color: #ff7500;
                            border-color: #ff7500
                        }

                        .td_uid_51_5804cf9573edb_rand .block-title span, .td_uid_51_5804cf9573edb_rand .td-trending-now-title, .td_uid_51_5804cf9573edb_rand .block-title a, .td_uid_51_5804cf9573edb_rand .td-read-more a, .td_uid_51_5804cf9573edb_rand .td-weather-information:before, .td_uid_51_5804cf9573edb_rand .td-weather-week:before, .td_uid_51_5804cf9573edb_rand .td-subcat-dropdown:hover .td-subcat-more, .td_uid_51_5804cf9573edb_rand .td-exchange-header:before, .td_uid_51_5804cf9573edb_rand .td-post-category:hover {
                            background-color: #ff7500
                        }

                        .td_uid_51_5804cf9573edb_rand .block-title {
                            border-color: #ff7500
                        }</style>
                    <script>var block_td_uid_51_5804cf9573edb = new tdBlock();
                        block_td_uid_51_5804cf9573edb.id = "td_uid_51_5804cf9573edb";
                        block_td_uid_51_5804cf9573edb.atts = '{"limit":"1","sort":"","post_ids":"","tag_slug":"recipe","autors_id":"","installed_post_types":"","category_id":"18","category_ids":"","custom_title":"HOLIDAY RECIPES","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"#ff7500","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_51_5804cf9573edb_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_51_5804cf9573edb.td_column_number = "1";
                        block_td_uid_51_5804cf9573edb.block_type = "td_block_6";
                        block_td_uid_51_5804cf9573edb.post_count = "1";
                        block_td_uid_51_5804cf9573edb.found_posts = "1";
                        block_td_uid_51_5804cf9573edb.header_color = "#ff7500";
                        block_td_uid_51_5804cf9573edb.ajax_pagination_infinite_stop = "";
                        block_td_uid_51_5804cf9573edb.max_num_pages = "1";
                        tdBlocksArray.push(block_td_uid_51_5804cf9573edb);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>HOLIDAY RECIPES</span></h4>
                    </div>
                    <div id=td_uid_51_5804cf9573edb class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_5 td_module_wrap td-animation-stack">
                                <h3 class="entry-title td-module-title"><a
                                        href="td-post-pasta-with-caramelised-onions-and-yogurt-recipe/index.html"
                                        rel=bookmark
                                        title="Pasta with caramelised onions and yogurt recipe">Pasta with
                                        caramelised onions and yogurt recipe</a></h3>
                                <div class=td-module-meta-info>
                                    <span class=td-post-author-name><a href="author/admin/index.html">Armin Vans</a> <span>-</span> </span>
                                        <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                       datetime="2015-03-22T05:27:37+00:00">Mar 22, 2015</time></span>
                                    <div class=td-module-comments><a
                                            href="td-post-pasta-with-caramelised-onions-and-yogurt-recipe/index.html#comments">1</a>
                                    </div>
                                </div>
                                <div class=td-module-image>
                                    <div class=td-module-thumb><a
                                            href="td-post-pasta-with-caramelised-onions-and-yogurt-recipe/index.html"
                                            rel=bookmark
                                            title="Pasta with caramelised onions and yogurt recipe"><img
                                                width=324 height=235 class=entry-thumb
                                                src="wp-content/uploads/2015/03/juice-324x235.jpg" alt=""
                                                title="Pasta with caramelised onions and yogurt recipe"/></a>
                                    </div>
                                    <a href="category/tagdiv-lifestyle/tagdiv-recipes/index.html"
                                       class=td-post-category>Recipes</a></div>
                                <div class=td-excerpt>
                                    The model is talking about booking her latest gig, modeling WordPress
                                    underwear in the brand latest Perfectly Fit campaign, which was shot by
                                    Lachian...
                                </div>
                                <div class=td_quote_on_blocks>How to mix the perfect juice</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
