<div class="vc_row wpb_row td-pb-row">
    <div class="wpb_column vc_column_container td-pb-span12">
        <div class="vc_column-inner ">
            <div class=wpb_wrapper>
                <div class="td-a-rec td-a-rec-id-custom_ad_1">
                    <div class="td-visible-desktop">
                        <div class="adsoptimal-slot" style="width: 728px; height: 90px;"></div>
                    </div>
                    <div class="td-visible-tablet-landscape">
                        <div class="adsoptimal-slot" style="width: 728px; height: 90px;"></div>
                    </div>
                    <div class="td-visible-tablet-portrait">
                        <div class="adsoptimal-slot" style="width: 728px; height: 90px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
