<?php
$arr_content = $this->arrContentList;
$keyDetail = $this->arrKeyDetail;
$word = $this->keyword;
?>

<div class="content page-search">
    <h1>Từ khóa: "<?php echo $word ?>" (<?php echo $this->intTotal ?> kết quả)</h1>
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
<!--        <img src="--><?php //echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/640x60.png'; ?><!--">-->
<!--                <ins class="adsbygoogle"-->
<!--                     style="display:inline-block;width: 640px;height: 60px"-->
<!--                     data-ad-client="ca-pub-5263187211037791"-->
<!--                     data-ad-slot="8521797908"></ins>-->
<!--                <script>-->
<!--                    (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--                </script>-->
    </div>
    <?php if($arr_content){ ?>
        <div class="listview clearfix">
            <ul>
                <?php foreach($arr_content as $content):
                        ?>
                        <li class="listitem clearfix">
                            <a class="title"
                               href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                                <?php echo $content['cont_title'] ?>
                            </a>
                            <a class="thumb"
                               href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                                <img src="<?php echo $content['cont_main_image'] ?>"
                                     alt="<?php echo $content['cont_title'] ?>">
                            </a>
                            <div class="desc"><?php echo $content['cont_description'] ?></div>

                            <?php if($content['list_keyword']){ ?>
                                <div class="tag">
                                    <ul class="td-tags-keyword clearfix">
                                        <li><span>Xem thêm: </span></li>
                                        <?php foreach ($content['list_keyword'] as $keyword) { ?>
                                            <li>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'],'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </div>
                            <?php } ?>

                        </li>
                    <?php endforeach;
                ?>
            </ul>
        </div>

        <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
<!--            <img src="--><?php //echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/640x60.png'; ?><!--">-->
<!--                    <ins class="adsbygoogle"-->
<!--                         style="display:inline-block;width: 640px;height: 60px"-->
<!--                         data-ad-client="ca-pub-5263187211037791"-->
<!--                         data-ad-slot="8521797908"></ins>-->
<!--                    <script>-->
<!--                        (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--                    </script>-->
        </div>
        
    <?php } else { ?>
        <div class="summary-info">Không tìm thấy kết quả phù hợp với <b><?php echo $word ?></b></div>
    <?php } ?>
</div>