<?php
$keyDetail = $this->arrKeyDetail;
$arr_content = $this->arrContentList;
$content_crawler = $keyDetail['content_crawler']!= '1' ? json_decode($keyDetail['content_crawler'], true) : '1';
?>
<div class="content">
    <h1><?php echo $keyDetail['key_name'] ?></h1>
    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
            <!-- TT360 Category -->
            <ins class="adsbygoogle"
                 style="display:inline-block;"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="5007199245"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>

    <div class="listview clearfix">
        <ul>
            <?php for($i = 0; $i <= 2; $i ++):
                if(isset($arr_content[$i])):
                    ?>
                    <li class="listitem clearfix">
                        <a class="title"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                            <?php echo $arr_content[$i]['cont_title'] ?>
                        </a>
                        <a class="thumb"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                            <img src="<?php echo $arr_content[$i]['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content[$i]['cont_title'] ?>">
                        </a>
                        <div class="desc"><?php echo $arr_content[$i]['cont_description'] ?></div>

                        <?php if($arr_content[$i]['list_keyword']){ ?>
                            <div class="tag">
                                <ul class="td-tags-keyword clearfix">
                                    <li><span>Xem thêm: </span></li>
                                    <?php foreach ($arr_content[$i]['list_keyword'] as $keyword) { ?>
                                        <li>
                                            <a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'],'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        <?php } ?>

                    </li>
                <?php endif; endfor;
            ?>
        </ul>
    </div>

    <div id="adindexcenter" class="adbox" style="margin-bottom:20px;">
        <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
            <!-- TT360 Category -->
            <ins class="adsbygoogle"
                 style="display:inline-block;"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="5007199245"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>

    <div class="content_gg">
        <?php if($content_crawler != '1'){ ?>
            <div class="td-post-content" style="margin-top: 0px">
                <?php foreach ($content_crawler as $item){ ?>
                    <p style="margin-bottom: 10px"><?php echo $item['description'] ?></p>
                <?php } ?>
            </div>
        <?php } ?>
    </div>

    <div class="listview clearfix">
        <ul>
            <?php for($i = 3; $i <= 9; $i ++):
                if(isset($arr_content[$i])):
                    ?>
                    <li class="listitem clearfix">
                        <a class="title"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                            <?php echo $arr_content[$i]['cont_title'] ?>
                        </a>
                        <a class="thumb"
                           href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arr_content[$i]['cont_slug'], 'contentId' => $arr_content[$i]['cont_id']]) ?>">
                            <img src="<?php echo $arr_content[$i]['cont_main_image'] ?>"
                                 alt="<?php echo $arr_content[$i]['cont_title'] ?>">
                        </a>
                        <div class="desc"><?php echo $arr_content[$i]['cont_description'] ?></div>

                        <?php if($arr_content[$i]['list_keyword']){ ?>
                            <div class="tag">
                                <ul class="td-tags-keyword clearfix">
                                    <li><span>Xem thêm: </span></li>
                                    <?php foreach ($arr_content[$i]['list_keyword'] as $keyword) { ?>
                                        <li>
                                            <a href="<?php echo $this->serverUrl() . $this->Url('keyword', ['keyId' => $keyword['key_id'],'keySlug' => $keyword['key_slug']]) ?>"><?php echo $keyword['key_name'] ?></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </div>
                        <?php } ?>

                    </li>
                <?php endif; endfor;
            ?>
        </ul>
    </div>

    <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
        <div id="adsinfeed" class="adbox" style="margin-bottom:20px">
            <!-- TT360 Category -->
            <ins class="adsbygoogle"
                 style="display:inline-block;"
                 data-ad-client="ca-pub-9166980393030854"
                 data-ad-slot="5007199245"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
</div>
