<!-- FOOTER -->
<div class=td-footer-wrapper>
    <div class=td-container>
        <div class=td-pb-row>
            <div class=td-pb-span12>
            </div>
        </div>
        <div class=td-pb-row>
            <div class=td-pb-span4>
                <div class="td_block_wrap td_block_7 td_uid_60_5804cf95890de_rand td-pb-border-top"
                     data-td-block-uid=td_uid_60_5804cf95890de>
                    <script>var block_td_uid_60_5804cf95890de = new tdBlock();
                        block_td_uid_60_5804cf95890de.id = "td_uid_60_5804cf95890de";
                        block_td_uid_60_5804cf95890de.atts = '{"limit":3,"sort":"featured","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"","category_ids":"","custom_title":"EDITOR PICKS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_60_5804cf95890de_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_60_5804cf95890de.td_column_number = "1";
                        block_td_uid_60_5804cf95890de.block_type = "td_block_7";
                        block_td_uid_60_5804cf95890de.post_count = "3";
                        block_td_uid_60_5804cf95890de.found_posts = "17";
                        block_td_uid_60_5804cf95890de.header_color = "";
                        block_td_uid_60_5804cf95890de.ajax_pagination_infinite_stop = "";
                        block_td_uid_60_5804cf95890de.max_num_pages = "6";
                        tdBlocksArray.push(block_td_uid_60_5804cf95890de);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>EDITOR PICKS</span></h4></div>
                    <div id=td_uid_60_5804cf95890de class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="wordpress-news-magazine-charts-the-most-fashionable-new-york-couples-in-2016/index.html"
                                        rel=bookmark
                                        title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2016/01/couple-100x70.jpg" alt=""
                                            title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="wordpress-news-magazine-charts-the-most-fashionable-new-york-couples-in-2016/index.html"
                                            rel=bookmark
                                            title="WordPress News Magazine Charts the Most Fashionable New York Couples in 2016">WordPress
                                            News Magazine Charts the Most Fashionable New York Couples in...</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2016-01-22T05:58:41+00:00">Jan 22, 2016</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="the-most-anticipated-charter-flights-in-the-canary-islands/index.html"
                                        rel=bookmark
                                        title="The Most Anticipated Charter Flights in the Canary Islands"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2015/02/plane-100x70.jpg" alt=""
                                            title="The Most Anticipated Charter Flights in the Canary Islands"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="the-most-anticipated-charter-flights-in-the-canary-islands/index.html"
                                            rel=bookmark
                                            title="The Most Anticipated Charter Flights in the Canary Islands">The
                                            Most Anticipated Charter Flights in the Canary Islands</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2016-01-22T05:47:36+00:00">Jan 22, 2016</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="15-grooming-techniques-every-man-needs-to-know/index.html"
                                        rel=bookmark title="15 Grooming Techniques Every Man Needs to Know"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2015/02/bike-100x70.jpg" alt=""
                                            title="15 Grooming Techniques Every Man Needs to Know"/></a></div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="15-grooming-techniques-every-man-needs-to-know/index.html"
                                            rel=bookmark title="15 Grooming Techniques Every Man Needs to Know">15
                                            Grooming Techniques Every Man Needs to Know</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2016-01-22T05:23:51+00:00">Jan 22, 2016</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=td-pb-span4>
                <div class="td_block_wrap td_block_7 td_uid_61_5804cf958a35b_rand td-pb-border-top"
                     data-td-block-uid=td_uid_61_5804cf958a35b>
                    <script>var block_td_uid_61_5804cf958a35b = new tdBlock();
                        block_td_uid_61_5804cf958a35b.id = "td_uid_61_5804cf958a35b";
                        block_td_uid_61_5804cf958a35b.atts = '{"limit":3,"sort":"popular","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"","category_ids":"","custom_title":"POPULAR POSTS","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"","header_color":"","header_text_color":"","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_uid_61_5804cf958a35b_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
                        block_td_uid_61_5804cf958a35b.td_column_number = "1";
                        block_td_uid_61_5804cf958a35b.block_type = "td_block_7";
                        block_td_uid_61_5804cf958a35b.post_count = "3";
                        block_td_uid_61_5804cf958a35b.found_posts = "161";
                        block_td_uid_61_5804cf958a35b.header_color = "";
                        block_td_uid_61_5804cf958a35b.ajax_pagination_infinite_stop = "";
                        block_td_uid_61_5804cf958a35b.max_num_pages = "54";
                        tdBlocksArray.push(block_td_uid_61_5804cf958a35b);</script>
                    <div class=td-block-title-wrap><h4 class=block-title><span>POPULAR POSTS</span></h4></div>
                    <div id=td_uid_61_5804cf958a35b class=td_block_inner>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="10-landscapes-wont-even-imagined-exist/index.html" rel=bookmark
                                        title="10 Landscapes You Won’t Have Even Imagined Exist"><img width=100
                                                                                                      height=70
                                                                                                      class=entry-thumb
                                                                                                      src="wp-content/uploads/2015/03/travel-girl-100x70.jpg"
                                                                                                      alt=""
                                                                                                      title="10 Landscapes You Won’t Have Even Imagined Exist"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="10-landscapes-wont-even-imagined-exist/index.html" rel=bookmark
                                            title="10 Landscapes You Won’t Have Even Imagined Exist">10 Landscapes
                                            You Won’t Have Even Imagined Exist</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-03-22T05:47:34+00:00">Mar 22, 2015</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                        rel=bookmark title="Decorating to Celebrate the Great Outdoor Space"><img
                                            width=100 height=70 class=entry-thumb
                                            src="wp-content/uploads/2015/01/outside-100x70.jpg" alt=""
                                            title="Decorating to Celebrate the Great Outdoor Space"/></a></div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="decorating-to-celebrate-the-great-outdoor-space/index.html"
                                            rel=bookmark title="Decorating to Celebrate the Great Outdoor Space">Decorating
                                            to Celebrate the Great Outdoor Space</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-01-22T05:46:01+00:00">Jan 22, 2015</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class=td-block-span12>
                            <div class="td_module_6 td_module_wrap td-animation-stack">
                                <div class=td-module-thumb><a
                                        href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                        rel=bookmark
                                        title="Zeta Architecture: Hexagon is the new circle in 2016"><img width=100
                                                                                                          height=70
                                                                                                          class=entry-thumb
                                                                                                          src="wp-content/uploads/2015/01/house-interior-100x70.jpg"
                                                                                                          alt=""
                                                                                                          title="Zeta Architecture: Hexagon is the new circle in 2016"/></a>
                                </div>
                                <div class=item-details>
                                    <h3 class="entry-title td-module-title"><a
                                            href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html"
                                            rel=bookmark
                                            title="Zeta Architecture: Hexagon is the new circle in 2016">Zeta
                                            Architecture: Hexagon is the new circle in 2016</a></h3>
                                    <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-01-22T05:44:07+00:00">Jan 22, 2015</time></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class=td-pb-span4>
                <div class="td_block_wrap td_block_popular_categories td_uid_62_5804cf958b368_rand widget widget_categories td-pb-border-top"
                     data-td-block-uid=td_uid_62_5804cf958b368><h4 class=block-title><span>POPULAR CATEGORY</span>
                    </h4>
                    <ul class=td-pb-padding-side>
                        <li><a href="category/tagdiv-technology/tagdiv-gadgets/index.html">Gadgets<span
                                    class=td-cat-no>15</span></a></li>
                        <li><a href="category/tagdiv-design/tagdiv-architecture/index.html">Architecture<span
                                    class=td-cat-no>15</span></a></li>
                        <li><a href="category/tagdiv-fashion/tagdiv-new-look-2015/index.html">New look 2016<span
                                    class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-technology/tagdiv-reviews/index.html">Reviews<span
                                    class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-technology/tagdiv-mobile-and-phones/index.html">Mobile and
                                Phones<span class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-lifestyle/tagdiv-recipes/index.html">Recipes<span
                                    class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-design/tagdiv-decorating/index.html">Decorating<span
                                    class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-design/tagdiv-interiors/index.html">Interiors<span
                                    class=td-cat-no>14</span></a></li>
                        <li><a href="category/tagdiv-fashion/tagdiv-street-fashion/index.html">Street fashion<span
                                    class=td-cat-no>13</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class=td-footer-bottom-full>
        <div class=td-container>
            <div class=td-pb-row>
                <div class=td-pb-span3>
                    <aside class=footer-logo-wrap><a href="index.html"><img class=td-retina-data
                                                                            src="wp-content/uploads/2016/01/logo-white.png"
                                                                            data-retina="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/logo-white@2x.png"
                                                                            alt="" title=""/></a></aside>
                </div>
                <div class=td-pb-span5>
                    <aside class=footer-text-wrap>
                        <div class=block-title><span>ABOUT US</span></div>
                        Newspaper is your news, entertainment, music fashion website. We provide you with the latest
                        breaking news and videos straight from the entertainment industry.
                        <div class=footer-email-wrap>Contact us: <a href="mailto:contact@yoursite.com">contact@yoursite.com</a>
                        </div>
                    </aside>
                </div>
                <div class=td-pb-span4>
                    <aside class="footer-social-wrap td-social-style-2">
                        <div class=block-title><span>FOLLOW US</span></div>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Facebook>
<i class="td-icon-font td-icon-facebook"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Twitter>
<i class="td-icon-font td-icon-twitter"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Vimeo>
<i class="td-icon-font td-icon-vimeo"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=VKontakte>
<i class="td-icon-font td-icon-vk"></i>
</a>
</span>
<span class=td-social-icon-wrap>
<a target=_blank href="#" title=Youtube>
<i class="td-icon-font td-icon-youtube"></i>
</a>
</span></aside>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- END FOOTER -->

<!-- LINE FOOTER -->
<div class=td-sub-footer-container>
    <div class=td-container>
        <div class=td-pb-row>
            <div class="td-pb-span7 td-sub-footer-menu">
                <div class=menu-footer-menu-container>
                    <ul id=menu-footer-menu class=td-subfooter-menu>
                        <li id=menu-item-16
                            class="menu-item menu-item-type-custom menu-item-object-custom menu-item-first td-menu-item td-normal-menu menu-item-16">
                            <a href="#">Disclaimer</a></li>
                        <li id=menu-item-17
                            class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-17">
                            <a href="#">Privacy</a></li>
                        <li id=menu-item-18
                            class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-18">
                            <a href="#">Advertisement</a></li>
                        <li id=menu-item-19
                            class="menu-item menu-item-type-custom menu-item-object-custom td-menu-item td-normal-menu menu-item-19">
                            <a href="#">Contact us</a></li>
                    </ul>
                </div>
            </div>
            <div class="td-pb-span5 td-sub-footer-copy">
                &copy; Copyright 2016 - Newspaper by TagDiv
            </div>
        </div>
    </div>
</div>

<!-- END LINE FOOTER -->	