<?php
$arr_category = unserialize(ARR_CATEGORY_INFO);
?>

<!--[Header]-->
<div id="header">
    <div class="headerleft">
        <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>" id="logo" title=""></a>
    </div>
    <div id="searchBox">
        <form method="get" action="<?php echo $this->serverUrl() . $this->Url('search') ?>" id="cse-search-box">
            <div>

                <input type="text" name="word" size="55" id="q" placeholder="Tìm kiếm"/>
                <input type="submit" value="Tìm" id="btnHeaderFind"/>

            </div>
        </form>
    </div>
    <a class="toggle menu"></a>
    <a class="toggle search"></a>
</div>

<!--[Menu]-->
<div id="mainmenu">
    <ul id="topnav" class="navigation clearfix">
        <li class="item">
            <a href="<?php echo $this->serverUrl() . $this->Url('home') ?>">
                <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/icon/home.png'; ?>"/>
                Trang chủ
            </a>
        </li>
        <?php foreach ($arr_category as $cate) { ?>
            <li class="item tax-<?php echo $cate['cate_slug'] ?>">
                <a href='<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate['cate_slug'], 'cateId' => $cate['cate_id']]) ?>'>
                    <img
                        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/icon/' . $cate['cate_icon'] . '.png'; ?>"/>
                    <?php echo $cate['cate_name'] ?>
                </a>
            </li>
        <?php } ?>
        <li class="item tax-keyword">
            <a href='<?php echo $this->serverUrl() . $this->Url('list-keyword', ['page' => 1]); ?>'>
                <img src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/icon/Greentech.png'; ?>"/>
                Keyword
            </a>
        </li>
    </ul>
</div>

 