<!DOCTYPE html>
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<head>
    <meta charset="utf-8">

    <?php echo $this->MyHeadTitle(); ?>

    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <meta property="fb:app_id" content="265611626917890"/>

    <?php
    echo $this->headMeta();
    ?>

    <link rel=stylesheet href='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/css/style.css'; ?>'
          type='text/css'/>

    <meta name="apple-mobile-web-app-title" content="Tintuc360.site"/>
    <meta name="application-name" content="Tintuc360.site"/>
    <link rel="apple-touch-icon" href="favicon.192.png"/>
    <link rel="icon" sizes="192x192" href="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/images/favicon.png'; ?>"/>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-89373434-1', 'auto');
	  ga('send', 'pageview');

	</script>
</head>
<body>
<div id="main" class="cp7">
    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/header')); ?>

    <div class="clear"></div>

    <div id="contentMain" class="clearfix">

        <?php echo \My\Minifier\HtmlMin::minify($this->layout()->content); ?>
        <div class="sidebar">
            <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/sidebar')); ?>
        </div>
        <div class="leftbar">
            <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/leftbar')); ?>
        </div>
    </div>

    <div class="clear"></div>

    <div id="footer" class="clearfix">
        <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/footer')); ?>
    </div>
</div>

<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.validate.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.validate.unobtrusive.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.raty.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.sticky.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.cookie.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery.bxslider.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/ads/adfooter.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/ads/meta.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/ads/adengine.v5.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/photoswipe/photoswipe.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/photoswipe/photoswipe-ui-default.min.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/photoswipe/jquery.photoswipe.js'; ?>"></script>
<script type="text/javascript"
        src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/main.js'; ?>"></script>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

</body>
</html>
