<!doctype html >
<!--[if IE 8]>
<html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang=en-US> <!--<![endif]-->
<meta http-equiv="content-type" content="text/html;charset=UTF-8"/><!-- /Added by HTTrack -->
<head>
    <title>Newspaper 7 | The Best News Magazine WordPress Theme by tagDiv</title>
    <meta charset=UTF-8/>
    <meta name=viewport content="width=device-width, initial-scale=1.0">
    <link rel=pingback href="xmlrpc.php"/>
    <link rel=icon type="image/png" href="wp-content/uploads/2016/01/favicon.png">
    <link rel=alternate type="application/rss+xml" title="Newspaper 7 &raquo; Feed" href="feed/index.html"/>
    <link rel=alternate type="application/rss+xml" title="Newspaper 7 &raquo; Comments Feed"
          href="comments/feed/index.html"/>
    <link rel=alternate type="application/rss+xml" title="Newspaper 7 &raquo; Homepage Comments Feed"
          href="homepage/feed/index.html"/>

    <script type="text/javascript">window._wpemojiSettings = {
            "baseUrl": "https:\/\/s.w.org\/images\/core\/emoji\/72x72\/",
            "ext": ".png",
            "source": {"concatemoji": "http:\/\/demo.tagdiv.com\/newspaper\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.5.3"}
        };
        !function (a, b, c) {
            function d(a) {
                var c, d, e, f = b.createElement("canvas"), g = f.getContext && f.getContext("2d"), h = String.fromCharCode;
                if (!g || !g.fillText)return !1;
                switch (g.textBaseline = "top", g.font = "600 32px Arial", a) {
                    case"flag":
                        return g.fillText(h(55356, 56806, 55356, 56826), 0, 0), f.toDataURL().length > 3e3;
                    case"diversity":
                        return g.fillText(h(55356, 57221), 0, 0), c = g.getImageData(16, 16, 1, 1).data, d = c[0] + "," + c[1] + "," + c[2] + "," + c[3], g.fillText(h(55356, 57221, 55356, 57343), 0, 0), c = g.getImageData(16, 16, 1, 1).data, e = c[0] + "," + c[1] + "," + c[2] + "," + c[3], d !== e;
                    case"simple":
                        return g.fillText(h(55357, 56835), 0, 0), 0 !== g.getImageData(16, 16, 1, 1).data[0];
                    case"unicode8":
                        return g.fillText(h(55356, 57135), 0, 0), 0 !== g.getImageData(16, 16, 1, 1).data[0]
                }
                return !1
            }

            function e(a) {
                var c = b.createElement("script");
                c.src = a, c.type = "text/javascript", b.getElementsByTagName("head")[0].appendChild(c)
            }

            var f, g, h, i;
            for (i = Array("simple", "flag", "unicode8", "diversity"), c.supports = {
                everything: !0,
                everythingExceptFlag: !0
            }, h = 0; h < i.length; h++)c.supports[i[h]] = d(i[h]), c.supports.everything = c.supports.everything && c.supports[i[h]], "flag" !== i[h] && (c.supports.everythingExceptFlag = c.supports.everythingExceptFlag && c.supports[i[h]]);
            c.supports.everythingExceptFlag = c.supports.everythingExceptFlag && !c.supports.flag, c.DOMReady = !1, c.readyCallback = function () {
                c.DOMReady = !0
            }, c.supports.everything || (g = function () {
                c.readyCallback()
            }, b.addEventListener ? (b.addEventListener("DOMContentLoaded", g, !1), a.addEventListener("load", g, !1)) : (a.attachEvent("onload", g), b.attachEvent("onreadystatechange", function () {
                "complete" === b.readyState && c.readyCallback()
            })), f = c.source || {}, f.concatemoji ? e(f.concatemoji) : f.wpemoji && f.twemoji && (e(f.twemoji), e(f.wpemoji)))
        }(window, document, window._wpemojiSettings);
    </script>

    <style type="text/css">img.wp-smiley, img.emoji {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -.1em !important;
            background: none !important;
            padding: 0 !important
        }
    </style>
    <!--    <link rel=stylesheet id=contact-form-7-css-->
    <!--          href='wp-content/plugins/contact-form-7/includes/css/A.styles.css%2cqver%3d4.5.1.pagespeed.cf.ZPvL_THC9x.css'-->
    <!--          type='text/css' media=all/>-->
    <link rel=stylesheet id=google_font_open_sans-css
          href='http://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C400%2C600%2C700&amp;ver=4.5.3'
          type='text/css' media=all/>
    <link rel=stylesheet id=google_font_roboto-css
          href='http://fonts.googleapis.com/css?family=Roboto%3A500%2C400italic%2C700%2C900%2C500italic%2C400%2C300&amp;ver=4.5.3'
          type='text/css' media=all/>
    <link rel=stylesheet id=js_composer_front-css
          href='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/css/js_composer.min2720.css'; ?>' type='text/css'
          media=all/>
    <link rel=stylesheet id=td-theme-css
          href='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/css/A.style.css,qver=7.3_d99.pagespeed.cf.c8A9VtP5SH.css'; ?>'
          type='text/css' media="screen"/>

    <script type='text/javascript'
            src='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jqueryb8ff.js' ?>'></script>
    <script type='text/javascript'
            src='<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/jquery-migrate.min330a.js' ?>'></script>


    <link rel='https://api.w.org/' href='wp-json/index.html'/>
    <link rel=EditURI type="application/rsd+xml" title=RSD href="xmlrpc0db0.php?rsd"/>
    <link rel=wlwmanifest type="application/wlwmanifest+xml" href="wp-includes/wlwmanifest.xml"/>
    <meta name=generator content="WordPress 4.5.3"/>
    <link rel=canonical href="index.html"/>
    <link rel=shortlink href='index.html'/>
    <link rel=alternate type="application/json+oembed"
          href="wp-json/oembed/1.0/embed9d2e.json?url=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2F"/>
    <link rel=alternate type="text/xml+oembed"
          href="wp-json/oembed/1.0/embedbf2a?url=http%3A%2F%2Fdemo.tagdiv.com%2Fnewspaper%2F&amp;format=xml"/>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <style type="text/css">.recentcomments a {
            display: inline !important;
            padding: 0 !important;
            margin: 0 !important
        }</style>
    <meta name=generator content="Powered by Visual Composer - drag and drop page builder for WordPress."/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" type="text/css"
          href="http://demo.tagdiv.com/newspaper/wp-content/plugins/js_composer/assets/css/vc_lte_ie9.min.css"
          media="screen"><![endif]--><!--[if IE  8]>
    <link rel="stylesheet" type="text/css"
          href="http://demo.tagdiv.com/newspaper/wp-content/plugins/js_composer/assets/css/vc-ie8.min.css"
          media="screen"><![endif]-->

    <?php
    echo $this->headLink();
    ?>

<!--    <script type='text/javascript'-->
<!--            src='--><?php //echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE . '/js/library/tagdiv_theme.min3688.js' ?><!--'></script>-->

    <script>
        var td_is_safari = false;
        var td_is_ios = false;
        var td_is_windows_phone = false;
        var ua = navigator.userAgent.toLowerCase();
        var td_is_android = ua.indexOf('android') > -1;
        if (ua.indexOf('safari') != -1) {
            if (ua.indexOf('chrome') > -1) {
            } else {
                td_is_safari = true;
            }
        }
        if (navigator.userAgent.match(/(iPhone|iPod|iPad)/i)) {
            td_is_ios = true;
        }
        if (navigator.userAgent.match(/Windows Phone/i)) {
            td_is_windows_phone = true;
        }
        if (td_is_ios || td_is_safari || td_is_windows_phone || td_is_android) {
            if (top.location != location) {
                top.location.replace('index.html');
            }
        }
        var tdBlocksArray = [];
        function tdBlock() {
            this.id = '';
            this.block_type = 1;
            this.atts = '';
            this.td_column_number = '';
            this.td_current_page = 1;
            this.post_count = 0;
            this.found_posts = 0;
            this.max_num_pages = 0;
            this.td_filter_value = '';
            this.is_ajax_running = false;
            this.td_user_action = '';
            this.header_color = '';
            this.ajax_pagination_infinite_stop = '';
        }
        (function () {
            var htmlTag = document.getElementsByTagName("html")[0];
            if (navigator.userAgent.indexOf("MSIE 10.0") > -1) {
                htmlTag.className += ' ie10';
            }
            if (!!navigator.userAgent.match(/Trident.*rv\:11\./)) {
                htmlTag.className += ' ie11';
            }
            if (/(iPad|iPhone|iPod)/g.test(navigator.userAgent)) {
                htmlTag.className += ' td-md-is-ios';
            }
            var user_agent = navigator.userAgent.toLowerCase();
            if (user_agent.indexOf("android") > -1) {
                htmlTag.className += ' td-md-is-android';
            }
            if (-1 !== navigator.userAgent.indexOf('Mac OS X')) {
                htmlTag.className += ' td-md-is-os-x';
            }
            if (/chrom(e|ium)/.test(navigator.userAgent.toLowerCase())) {
                htmlTag.className += ' td-md-is-chrome';
            }
            if (-1 !== navigator.userAgent.indexOf('Firefox')) {
                htmlTag.className += ' td-md-is-firefox';
            }
            if (-1 !== navigator.userAgent.indexOf('Safari') && -1 === navigator.userAgent.indexOf('Chrome')) {
                htmlTag.className += ' td-md-is-safari';
            }
        })();
        var tdLocalCache = {};
        (function () {
            "use strict";
            tdLocalCache = {
                data: {}, remove: function (resource_id) {
                    delete tdLocalCache.data[resource_id];
                }, exist: function (resource_id) {
                    return tdLocalCache.data.hasOwnProperty(resource_id) && tdLocalCache.data[resource_id] !== null;
                }, get: function (resource_id) {
                    return tdLocalCache.data[resource_id];
                }, set: function (resource_id, cachedData) {
                    tdLocalCache.remove(resource_id);
                    tdLocalCache.data[resource_id] = cachedData;
                }
            };
        })();
        var tds_login_sing_in_widget = "show";
        var td_viewport_interval_list = [{"limitBottom": 767, "sidebarWidth": 228}, {
            "limitBottom": 1018,
            "sidebarWidth": 300
        }, {"limitBottom": 1140, "sidebarWidth": 324}];
        var td_animation_stack_effect = "type0";
        var tds_animation_stack = true;
        var td_animation_stack_specific_selectors = ".entry-thumb, img";
        var td_animation_stack_general_selectors = ".td-animation-stack img, .post img";
        var td_ajax_url = "";
        var td_get_template_directory_uri = "";
        var tds_snap_menu = "smart_snap_always";
        var tds_logo_on_sticky = "show_header_logo";
        var tds_header_style = "";
        var td_please_wait = "Please wait...";
        var td_email_user_pass_incorrect = "User or password incorrect!";
        var td_email_user_incorrect = "Email or username incorrect!";
        var td_email_incorrect = "Email incorrect!";
        var tds_more_articles_on_post_enable = "";
        var tds_more_articles_on_post_time_to_wait = "";
        var tds_more_articles_on_post_pages_distance_from_top = 0;
        var tds_theme_color_site_wide = "#4db2ec";
        var tds_smart_sidebar = "enabled";
        var tdThemeName = "Newspaper";
        var td_magnific_popup_translation_tPrev = "Previous (Left arrow key)";
        var td_magnific_popup_translation_tNext = "Next (Right arrow key)";
        var td_magnific_popup_translation_tCounter = "%curr% of %total%";
        var td_magnific_popup_translation_ajax_tError = "The content from %url% could not be loaded.";
        var td_magnific_popup_translation_image_tError = "The image #%curr% could not be loaded.";
        var td_ad_background_click_link = "";
        var td_ad_background_click_target = "";
    </script>
    <style>
        .block-title > span, .block-title > a, .block-title > label, .widgettitle, .widgettitle:after, .td-trending-now-title, .td-trending-now-wrapper:hover .td-trending-now-title, .wpb_tabs li.ui-tabs-active a, .wpb_tabs li:hover a, .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container .vc_tta-tab.vc_active > a, .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container .vc_tta-tab:hover > a, .td-related-title .td-cur-simple-item, .woocommerce .product .products h2, .td-subcat-filter .td-subcat-dropdown:hover .td-subcat-more, .td-weather-information:before, .td-weather-week:before, .td_block_exchange .td-exchange-header:before {
            background-color: #222
        }

        .woocommerce div.product .woocommerce-tabs ul.tabs li.active {
            background-color: #222 !important
        }

        .block-title, .td-related-title, .wpb_tabs .wpb_tabs_nav, .vc_tta-container .vc_tta-color-grey.vc_tta-tabs-position-top.vc_tta-style-classic .vc_tta-tabs-container, .woocommerce div.product .woocommerce-tabs ul.tabs:before {
            border-color: #222
        }

        .td-menu-background:before, .td-search-background:before {
            background: rgba(0, 0, 0, .5);
            background: -moz-linear-gradient(top, rgba(0, 0, 0, .5) 0%, rgba(0, 0, 0, .6) 100%);
            background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(0, 0, 0, .5)), color-stop(100%, rgba(0, 0, 0, .6)));
            background: -webkit-linear-gradient(top, rgba(0, 0, 0, .5) 0%, rgba(0, 0, 0, .6) 100%);
            background: -o-linear-gradient(top, rgba(0, 0, 0, 0.5) 0%, @mobileu_gradient_two_mob 100%);
            background: -ms-linear-gradient(top, rgba(0, 0, 0, .5) 0%, rgba(0, 0, 0, .6) 100%);
            background: linear-gradient(to bottom, rgba(0, 0, 0, .5) 0%, rgba(0, 0, 0, .6) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='rgba(0,0,0,0.5)', endColorstr='rgba(0,0,0,0.6)', GradientType=0)
        }

        .td-menu-background, .td-search-background {
            background-image: url(wp-content/uploads/2016/05/mobile-bg.jpg)
        }

        .white-popup-block:before {
            background-image: url(http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/05/login-mod.jpg)
        }</style>
    <noscript>
        <style type="text/css">.wpb_animate_when_almost_visible {
                opacity: 1
            }</style>
    </noscript>

</head>
<body
    class="home page page-id-13 page-template page-template-page-pagebuilder-latest page-template-page-pagebuilder-latest-php homepage wpb-js-composer js-comp-ver-4.11.2 vc_responsive td-animation-stack-type0 td-full-layout"
    itemscope=itemscope itemtype="http://schema.org/WebPage">

<!-- BUTTON SCROLL FOOTER -->
<div class=td-scroll-up><i class=td-icon-menu-up></i></div>
<!-- END BUTTON SCROLL FOOTER -->
<div class=td-menu-background></div>


<!-- MENU MOBILE -->
<div id=td-mobile-nav>
    <div class=td-mobile-container>
        <div class=td-menu-socials-wrap>
            <div class=td-menu-socials>
				<span class=td-social-icon-wrap>
				<a target=_blank href="#" title=Facebook>
				<i class="td-icon-font td-icon-facebook"></i>
				</a>
				</span>
				<span class=td-social-icon-wrap>
				<a target=_blank href="#" title=Twitter>
				<i class="td-icon-font td-icon-twitter"></i>
				</a>
				</span>
				<span class=td-social-icon-wrap>
				<a target=_blank href="#" title=Vimeo>
				<i class="td-icon-font td-icon-vimeo"></i>
				</a>
				</span>
				<span class=td-social-icon-wrap>
				<a target=_blank href="#" title=VKontakte>
				<i class="td-icon-font td-icon-vk"></i>
				</a>
				</span>
				<span class=td-social-icon-wrap>
				<a target=_blank href="#" title=Youtube>
				<i class="td-icon-font td-icon-youtube"></i>
				</a>
				</span>
            </div>
            <div class=td-mobile-close>
                <a href="#"><i class=td-icon-close-mobile></i></a>
            </div>
        </div>
        <div class=td-menu-login-section>
            <div class=td-guest-wrap>
                <div class=td-menu-avatar>
                    <div class=td-avatar-container>
                        <img src="http://1.gravatar.com/avatar/?s=80&amp;d=mm&amp;r=g"
                             width=80 height=80 alt=""
                             class="avatar avatar-80 wp-user-avatar wp-user-avatar-80 photo avatar-default"/>
                    </div>
                </div>
                <div class=td-menu-login><a id=login-link-mob>Sign in</a></div>
            </div>
        </div>
        <div class=td-mobile-content>
            <div class=menu-main-menu-container>
                <ul id=menu-main-menu class=td-mobile-main-menu>
                    <li id=menu-item-15
                        class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-13 current_page_item menu-item-first menu-item-15">
                        <a href="index.html">News</a></li>
                    <li id=menu-item-291
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-291">
                        <a href="category/tagdiv-fashion/index.html">Fashion<i
                                class="td-icon-menu-right td-element-after"></i></a>
                        <ul class=sub-menu>
                            <li id=menu-item-0 class=menu-item-0><a
                                    href="category/tagdiv-fashion/tagdiv-new-look-2015/index.html">New look 2016</a>
                            </li>
                            <li class=menu-item-0><a href="category/tagdiv-fashion/tagdiv-street-fashion/index.html">Street
                                    fashion</a></li>
                            <li class=menu-item-0><a href="category/tagdiv-fashion/tagdiv-style-hunter/index.html">Style
                                    hunter</a></li>
                            <li class=menu-item-0><a href="category/tagdiv-fashion/tagdiv-vogue/index.html">Vogue</a>
                            </li>
                        </ul>
                    </li>
                    <li id=menu-item-293
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-293"><a
                            href="category/tagdiv-technology/tagdiv-gadgets/index.html">Gadgets</a></li>
                    <li id=menu-item-308
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-308">
                        <a href="category/tagdiv-lifestyle/index.html">Lifestyle<i
                                class="td-icon-menu-right td-element-after"></i></a>
                        <ul class=sub-menu>
                            <li class=menu-item-0><a href="category/tagdiv-lifestyle/tagdiv-business/index.html">Business</a>
                            </li>
                            <li class=menu-item-0><a href="category/tagdiv-lifestyle/tagdiv-health-fitness/index.html">Health
                                    &amp; Fitness</a></li>
                            <li class=menu-item-0><a
                                    href="category/tagdiv-lifestyle/tagdiv-recipes/index.html">Recipes</a></li>
                            <li class=menu-item-0><a
                                    href="category/tagdiv-lifestyle/tagdiv-travel/index.html">Travel</a></li>
                        </ul>
                    </li>
                    <li id=menu-item-295
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-295"><a
                            href="category/tagdiv-video/index.html">Video</a></li>
                    <li id=menu-item-296
                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-296">
                        <a href="#">Features<i class="td-icon-menu-right td-element-after"></i></a>
                        <ul class=sub-menu>
                            <li id=menu-item-297
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-297">
                                <a href="#">Category layouts<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-310
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-310">
                                        <a href="#">Templates<i class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-796
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-796">
                                                <a href="category/template-style-1/index.html">Template style 1</a></li>
                                            <li id=menu-item-797
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-797">
                                                <a href="category/template-style-2/index.html">Template style 2</a></li>
                                        </ul>
                                    </li>
                                    <li id=menu-item-311
                                        class="td-demo-multicolumn-2 menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-311">
                                        <a href="#">Top posts style<i
                                                class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-812
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-812">
                                                <a href="category/grid-1/index.html">Grid 1</a></li>
                                            <li id=menu-item-813
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-813">
                                                <a href="category/grid-2/index.html">Grid 2</a></li>
                                            <li id=menu-item-1731
                                                class="td-demo-menuitem-hide menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1731">
                                                <a href="category/template-style-1/index.html">this is hidden</a></li>
                                        </ul>
                                    </li>
                                    <li id=menu-item-309
                                        class="td-demo-multicolumn-2 menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-309">
                                        <a href="#">Module list<i class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-821
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-821">
                                                <a href="category/module-1-layout/index.html">Module 1 layout</a></li>
                                            <li id=menu-item-822
                                                class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-822">
                                                <a href="category/module-2-layout/index.html">Module 2 layout</a></li>
                                            <li id=menu-item-1730
                                                class="td-demo-menuitem-hide menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1730">
                                                <a href="category/module-19-layout/index.html">this is hidden</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li id=menu-item-298
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-298">
                                <a href="#">Post templates<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-973
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-973"><a
                                            href="td-post-more-than-120-er-visits-linked-to-synthetic-marijuana-in-nyc-over-past-week/index.html">Default
                                            style</a></li>
                                    <li id=menu-item-974
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-974"><a
                                            href="td-post-400k-for-whisky-most-expensive-foods-and-drink-auctioned/index.html">Style
                                            1</a></li>
                                    <li id=menu-item-975
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-975"><a
                                            href="td-post-patricia-urquiola-coats-transparent-furniture-for-glas-italia-with-an-iridescent-sheen/index.html">Style
                                            2</a></li>
                                    <li id=menu-item-976
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-976"><a
                                            href="td-post-if-you-only-knew-how-much-your-relative-churn-rate-matters/index.html">Style
                                            3</a></li>
                                    <li id=menu-item-1943
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1943">
                                        <a href="15-grooming-techniques-every-man-needs-to-know/index.html">Style 4</a>
                                    </li>
                                </ul>
                            </li>
                            <li id=menu-item-299
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-299">
                                <a href="#">Smart lists<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-1229
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1229">
                                        <a href="smart-list-style-1/index.html">Smart List – Style 1</a></li>
                                    <li id=menu-item-1228
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1228">
                                        <a href="smart-list-style-2/index.html">Smart List – Style 2</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-312
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-312">
                                <a href="#">Premium Features <span class=td-menu-badge>NEW</span><i
                                        class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-2102
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2102">
                                        <a href="mobile-theme/index.html">Mobile theme</a></li>
                                    <li id=menu-item-2076
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2076">
                                        <a href="mobile-menu/index.html">Mobile menu</a></li>
                                    <li id=menu-item-1865
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1865">
                                        <a href="social-counter-widget/index.html">Social Counter</a></li>
                                    <li id=menu-item-1868
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1868">
                                        <a href="weather-widget/index.html">Weather widget</a></li>
                                    <li id=menu-item-1866
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1866">
                                        <a href="instagram-widget/index.html">Instagram widget</a></li>
                                    <li id=menu-item-1867
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1867">
                                        <a href="exchange-widget/index.html">Exchange widget</a></li>
                                    <li id=menu-item-1588
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1588">
                                        <a href="video-playlist/index.html">Video playlist</a></li>
                                    <li id=menu-item-1590
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1590">
                                        <a href="td-post-aston-villa-beat-liverpool-to-join-arsenal-in-the-fa-cup-final/index.html">tagDiv
                                            gallery</a></li>
                                    <li id=menu-item-1591
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1591">
                                        <a href="td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/index.html">Image
                                            lightbox</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-300
                                class="td-demo-multicolumn-2 menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-300">
                                <a href="#">Content blocks<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-497
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-497">
                                        <a href="block-1/index.html">Block 1</a></li>
                                    <li id=menu-item-508
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-508">
                                        <a href="block-2/index.html">Block 2</a></li>
                                    <li id=menu-item-511
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-511">
                                        <a href="block-3/index.html">Block 3</a></li>
                                    <li id=menu-item-1785
                                        class="td-demo-menuitem-hide menu-item menu-item-type-post_type menu-item-object-page menu-item-1785">
                                        <a href="big-grid-12/index.html">this is hidden</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-301
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-301">
                                <a href="#">Other blocks content<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-565
                                        class="td-demo-multicolumn-2 menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-565">
                                        <a href="#">Big Grid<i class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-608
                                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-608">
                                                <a href="big-grid-1/index.html">Big grid 1</a></li>
                                            <li id=menu-item-609
                                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-609">
                                                <a href="big-grid-2/index.html">Big grid 2</a></li>
                                        </ul>
                                    </li>
                                    <li id=menu-item-1608
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1608">
                                        <a href="big-grid-slide/index.html">Big grid slide</a></li>
                                    <li id=menu-item-621
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-621">
                                        <a href="ios-slider/index.html">IOS Slider</a></li>
                                    <li id=menu-item-631
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-631">
                                        <a href="news-ticker/index.html">News ticker</a></li>
                                    <li id=menu-item-636
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-636">
                                        <a href="homepage-one-top-post/index.html">Homepage post</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-302
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-302">
                                <a href="#">Shortcodes<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-669
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-669">
                                        <a href="blockquotes-pullquotes/index.html">Blockquotes &#038; Pullquotes</a>
                                    </li>
                                    <li id=menu-item-2072
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-2072">
                                        <a href="typography-formats/index.html">Typography formats</a></li>
                                    <li id=menu-item-668
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-668">
                                        <a href="grid-columns/index.html">Grid columns</a></li>
                                    <li id=menu-item-667
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-667">
                                        <a href="dropcaps/index.html">Dropcaps</a></li>
                                    <li id=menu-item-666
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-666">
                                        <a href="tabs-and-accordions/index.html">Tabs and Accordions</a></li>
                                    <li id=menu-item-665
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-665">
                                        <a href="lists/index.html">Lists</a></li>
                                    <li id=menu-item-664
                                        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-664">
                                        <a href="typology-and-html-elements/index.html">Typology and HTML elements</a>
                                    </li>
                                </ul>
                            </li>
                            <li id=menu-item-303
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-303">
                                <a href="#">Sidebars<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-1615
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1615">
                                        <a href="td-post-10-superfoods-that-lower-cholesterol/index.html">Left
                                            sidebar</a></li>
                                    <li id=menu-item-1612
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1612">
                                        <a href="td-post-five-things-you-may-have-missed-over-the-weekend-from-the-world-of-business/index.html">No
                                            sidebar</a></li>
                                    <li id=menu-item-1613
                                        class="menu-item menu-item-type-post_type menu-item-object-post menu-item-1613">
                                        <a href="td-post-microsoft-subsumes-open-tech-unit-back-inside-mothership/index.html">Right
                                            sidebar</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-304
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-304"><a
                                    target=_blank href="http://demo.tagdiv.com/newspaper_tech/shop">WooCommerce</a></li>
                            <li id=menu-item-305
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-305">
                                <a href="#">Pages<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-683
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-683">
                                        <a href="#">Embeds<i class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-684
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-684">
                                                <a href="td-post-vfx-techniques-creating-a-cg-flag-with-after-effects/index.html">Vimeo</a>
                                            </li>
                                            <li id=menu-item-688
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-688">
                                                <a href="td-post-lollapalooza-2014-chromeo-interview-with-dave-1-and-p-thugg/index.html">Youtube</a>
                                            </li>
                                            <li id=menu-item-691
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-691">
                                                <a href="td-post-what-happens-when-your-carryon-is-over-the-limit/index.html">Dailymotion</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li id=menu-item-692
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-692"><a
                                            href="author/admin/index.html">Author</a></li>
                                    <li id=menu-item-693
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-693"><a
                                            href="td-post-more-than-120-er-visits-linked-to-synthetic-marijuana-in-nyc-over-past-week/index.html#comments">Comments</a>
                                    </li>
                                    <li id=menu-item-697
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-697"><a
                                            href="no-page.html">404</a></li>
                                    <li id=menu-item-698
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-698"><a
                                            href="2015/index.html">Archive</a></li>
                                    <li id=menu-item-699
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-699"><a
                                            href="td-post-pasta-with-caramelised-onions-and-yogurt-recipe/attachment/57/index.html">Attachment</a>
                                    </li>
                                    <li id=menu-item-700
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-700"><a
                                            href="index84ab.html?s=food">Search</a></li>
                                    <li id=menu-item-701
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-701"><a
                                            href="tag/wordpress/index.html">Tag</a></li>
                                    <li id=menu-item-702
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-702"><a
                                            href="blog/index.html">Blog</a></li>
                                    <li id=menu-item-714
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-714"><a
                                            href="contact/index.html">Contact</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-306
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-306">
                                <a href="#">Reviews<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-738
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-738"><a
                                            href="td-post-intel-claims-new-ssd-750-drives-are-its-fastest-ever-for-desktop/index.html">Points
                                            review</a></li>
                                    <li id=menu-item-736
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-736"><a
                                            href="td-post-why-tech-accelerators-may-soon-be-as-irrelevant-as-an-mba/index.html">Stars
                                            review</a></li>
                                    <li id=menu-item-737
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-737"><a
                                            href="td-post-htc-nexus-8-with-64-bit-processor-4gb-of-ram-and-8mp-camera-leaks/index.html">Percent
                                            review</a></li>
                                </ul>
                            </li>
                            <li id=menu-item-739
                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-739">
                                <a href="#">Child menu<i class="td-icon-menu-right td-element-after"></i></a>
                                <ul class=sub-menu>
                                    <li id=menu-item-742
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-742">
                                        <a href="#">Sub-child menu<i
                                                class="td-icon-menu-right td-element-after"></i></a>
                                        <ul class=sub-menu>
                                            <li id=menu-item-743
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-743">
                                                <a href="#">Sub-child menu</a></li>
                                            <li id=menu-item-744
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-744">
                                                <a href="#">Sub-child menu</a></li>
                                            <li id=menu-item-745
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-745">
                                                <a href="#">Sub-child menu</a></li>
                                            <li id=menu-item-746
                                                class="menu-item menu-item-type-custom menu-item-object-custom menu-item-746">
                                                <a href="#">Sub-child menu</a></li>
                                        </ul>
                                    </li>
                                    <li id=menu-item-740
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-740"><a
                                            href="#">Sub-child menu</a></li>
                                    <li id=menu-item-741
                                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-741"><a
                                            href="#">Sub-child menu</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li id=menu-item-307
                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-307">
                        <a href="#">Homepages<i class="td-icon-menu-right td-element-after"></i></a>
                        <ul class=sub-menu>
                            <li id=menu-item-1094
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1094"><a
                                    href="homepage-fashion/index.html">Homepage – Fashion</a></li>
                            <li id=menu-item-1112
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1112"><a
                                    href="homepage-blog/index.html">Homepage – Blog</a></li>
                            <li id=menu-item-1109
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1109"><a
                                    href="homepage-video/index.html">Homepage – Video</a></li>
                            <li id=menu-item-1129
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1129"><a
                                    href="homepage-tech/index.html">Homepage – Tech</a></li>
                            <li id=menu-item-1123
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1123"><a
                                    href="homepage-sport/index.html">Homepage – Sport</a></li>
                            <li id=menu-item-1185
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1185"><a
                                    href="homepage-full-post-featured/index.html">Homepage – Full Post Featured</a></li>
                            <li id=menu-item-1140
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1140"><a
                                    href="homepage-newspaper/index.html">Homepage – Newspaper</a></li>
                            <li id=menu-item-1563
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1563"><a
                                    href="homepage-newsmag/index.html">Homepage – Newsmag</a></li>
                            <li id=menu-item-1195
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1195"><a
                                    href="homepage-magazine/index.html">Homepage – Magazine</a></li>
                            <li id=menu-item-1161
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1161"><a
                                    href="homepage-big-slide/index.html">Homepage – Big Slide</a></li>
                            <li id=menu-item-1137
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1137"><a
                                    href="homepage-infinite-scroll/index.html">Homepage – Infinite Scroll</a></li>
                            <li id=menu-item-1158
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1158"><a
                                    href="homepage-loop/index.html">Homepage – Loop</a></li>
                            <li id=menu-item-1167
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1167"><a
                                    href="homepage-less-images/index.html">Homepage – Less Images</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id=login-form-mobile class=td-register-section>
        <div id=td-login-mob class="td-login-animation td-login-hide-mob">
            <div class=td-login-close>
                <a href="#" class=td-back-button><i class=td-icon-read-down></i></a>
                <div class=td-login-title>Sign in</div>
                <div class=td-mobile-close>
                    <a href="#"><i class=td-icon-close-mobile></i></a>
                </div>
            </div>
            <div class=td-login-form-wrap>
                <div class=td-login-panel-title><span>Welcome!</span>Log into your account</div>
                <div class=td_display_err></div>
                <div class=td-login-inputs><input class=td-login-input type=text name=login_email id=login_email-mob
                                                  value="" required><label>your username</label></div>
                <div class=td-login-inputs><input class=td-login-input type=password name=login_pass id=login_pass-mob
                                                  value="" required><label>your password</label></div>
                <input type=button name=login_button id=login_button-mob class=td-login-button value="LOG IN">
                <div class=td-login-info-text><a href="#" id=forgot-pass-link-mob>Forgot your password?</a></div>
            </div>
        </div>
        <div id=td-forgot-pass-mob class="td-login-animation td-login-hide-mob">
            <div class=td-forgot-pass-close>
                <a href="#" class=td-back-button><i class=td-icon-read-down></i></a>
                <div class=td-login-title>Password recovery</div>
            </div>
            <div class=td-login-form-wrap>
                <div class=td-login-panel-title>Recover your password</div>
                <div class=td_display_err></div>
                <div class=td-login-inputs><input class=td-login-input type=text name=forgot_email id=forgot_email-mob
                                                  value="" required><label>your email</label></div>
                <input type=button name=forgot_button id=forgot_button-mob class=td-login-button value="Send My Pass">
            </div>
        </div>
    </div>
</div>

<!-- END MENU MOBILE -->


<div class=td-search-background></div>

<!-- SEARCH -->
<div class=td-search-wrap-mob>
    <div class=td-drop-down-search aria-labelledby=td-header-search-button>
        <form method=get class=td-search-form action="http://demo.tagdiv.com/newspaper/">
            <div class=td-search-close>
                <a href="#"><i class=td-icon-close-mobile></i></a>
            </div>
            <div role=search class=td-search-input>
                <span>Search</span>
                <input id=td-header-search-mob type=text value="" name=s autocomplete=off/>
            </div>
        </form>
        <div id=td-aj-search-mob></div>
    </div>
</div>

<!-- END SEARCH -->
<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>
<!-- CONTENT -->
<div id=td-outer-wrap>
    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/header')); ?>

    <div class="td-main-content-wrap">
        <div class="td-container">
            <?php
            if($controller == 'index' && $action == 'index'){
                echo \My\Minifier\HtmlMin::minify($this->layout()->content);
            } else {
            ?>
            <div class="td-pb-row">
                <!-- MAIN -->
                <div class="td-pb-span8 td-main-content" role="main">
                    <?php echo \My\Minifier\HtmlMin::minify($this->layout()->content); ?>
                </div>
                <!-- END MAIN -->
                <!-- LEFT -->
                <div class="td-pb-span4 td-main-sidebar" role="complementary">
                    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/nav-left')); ?>
                </div>
                <!-- END LEFT -->
            </div>
            <?php } ?>
        </div>
    </div>

    <?php echo \My\Minifier\HtmlMin::minify($this->render('frontend/footer')); ?>
</div>
<?php echo $this->headScript(); ?>
</body>
</html>
