<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$routeName = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch();
$controller = $paramsRouter['__CONTROLLER__'];
$action = $paramsRouter['action'];
?>
<div class=td-ss-main-sidebar>
    <div class="td-a-rec td-a-rec-id-sidebar  ">
        <div class=td-visible-desktop>
            <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                         style=max-width:300px
                                                                         src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                         alt="" width=300
                                                                         height=250/></a>
        </div>
        <div class=td-visible-tablet-landscape>
            <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                         style=max-width:300px
                                                                         src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                         alt="" width=300
                                                                         height=250/></a>
        </div>
        <div class=td-visible-tablet-portrait>
            <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                         style=max-width:200px
                                                                         src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec200.jpg"
                                                                         alt="" width=200
                                                                         height=200/></a>
        </div>
        <div class=td-visible-phone>
            <a href="http://themeforest.net/item/newspaper/5489609"><img class=td-retina
                                                                         style=max-width:300px
                                                                         src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2016/01/rec300.jpg"
                                                                         alt="" width=300
                                                                         height=250/></a>
        </div>
    </div>
    <div class="td_block_wrap td_block_1 td_block_widget td_uid_20_57fec2bd8bd22_rand td_with_ajax_pagination td-pb-border-top"
         data-td-block-uid=td_uid_20_57fec2bd8bd22>
        <script>var block_td_uid_20_57fec2bd8bd22 = new tdBlock();
            block_td_uid_20_57fec2bd8bd22.id = "td_uid_20_57fec2bd8bd22";
            block_td_uid_20_57fec2bd8bd22.atts = '{"limit":"4","sort":"popular","post_ids":"","tag_slug":"","autors_id":"","installed_post_types":"","category_id":"","category_ids":"","custom_title":"MUST READ","custom_url":"","show_child_cat":"","sub_cat_ajax":"","ajax_pagination":"next_prev","header_color":"#","header_text_color":"#","ajax_pagination_infinite_stop":"","td_column_number":1,"td_ajax_preloading":"","td_ajax_filter_type":"","td_ajax_filter_ids":"","td_filter_default_txt":"All","color_preset":"","border_top":"","class":"td_block_widget td_uid_20_57fec2bd8bd22_rand","offset":"","css":"","live_filter":"","live_filter_cur_post_id":"","live_filter_cur_post_author":""}';
            block_td_uid_20_57fec2bd8bd22.td_column_number = "1";
            block_td_uid_20_57fec2bd8bd22.block_type = "td_block_1";
            block_td_uid_20_57fec2bd8bd22.post_count = "4";
            block_td_uid_20_57fec2bd8bd22.found_posts = "161";
            block_td_uid_20_57fec2bd8bd22.header_color = "#";
            block_td_uid_20_57fec2bd8bd22.ajax_pagination_infinite_stop = "";
            block_td_uid_20_57fec2bd8bd22.max_num_pages = "41";
            tdBlocksArray.push(block_td_uid_20_57fec2bd8bd22);</script>
        <div class=td-block-title-wrap><h4 class=block-title><span>MUST READ</span></h4></div>
        <div id=td_uid_20_57fec2bd8bd22 class=td_block_inner>
            <div class=td-block-span12>
                <div class="td_module_4 td_module_wrap td-animation-stack">
                    <div class=td-module-image>
                        <div class=td-module-thumb><a
                                href="http://demo.tagdiv.com/newspaper/10-landscapes-wont-even-imagined-exist/"
                                rel=bookmark
                                title="10 Landscapes You Won’t Have Even Imagined Exist"><img
                                    width=324 height=235 class=entry-thumb
                                    src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/03/travel-girl-324x235.jpg"
                                    alt=""
                                    title="10 Landscapes You Won’t Have Even Imagined Exist"/></a></div>
                        <a href="http://demo.tagdiv.com/newspaper/category/tagdiv-lifestyle/tagdiv-travel/"
                           class=td-post-category>Travel</a></div>
                    <h3 class="entry-title td-module-title"><a
                            href="http://demo.tagdiv.com/newspaper/10-landscapes-wont-even-imagined-exist/"
                            rel=bookmark title="10 Landscapes You Won’t Have Even Imagined Exist">10
                            Landscapes You Won’t Have Even Imagined Exist</a></h3>
                    <div class=td-module-meta-info>
                                        <span class=td-post-author-name><a
                                                href="http://demo.tagdiv.com/newspaper/author/marius/">John Doe</a> <span>-</span> </span>
                                        <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                       datetime="2015-03-22T05:47:34+00:00">Mar 22, 2015</time></span>
                        <div class=td-module-comments><a
                                href="http://demo.tagdiv.com/newspaper/10-landscapes-wont-even-imagined-exist/#respond">0</a>
                        </div>
                    </div>
                    <div class=td-excerpt>
                        Prince Edward Island, Canada
                        Prince Edward Island is a Canadian province. It is one of the three Maritime
                        provinces and it is the smallest in...
                    </div>
                </div>
            </div>
            <div class=td-block-span12>
                <div class="td_module_6 td_module_wrap td-animation-stack">
                    <div class=td-module-thumb><a
                            href="http://demo.tagdiv.com/newspaper/decorating-to-celebrate-the-great-outdoor-space/"
                            rel=bookmark
                            title="Decorating to Celebrate the Great Outdoor Space"><img width=100
                                                                                         height=70
                                                                                         class=entry-thumb
                                                                                         src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/01/outside-100x70.jpg"
                                                                                         alt=""
                                                                                         title="Decorating to Celebrate the Great Outdoor Space"/></a>
                    </div>
                    <div class=item-details>
                        <h3 class="entry-title td-module-title"><a
                                href="http://demo.tagdiv.com/newspaper/decorating-to-celebrate-the-great-outdoor-space/"
                                rel=bookmark
                                title="Decorating to Celebrate the Great Outdoor Space">Decorating
                                to Celebrate the Great Outdoor Space</a></h3>
                        <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-01-22T05:46:01+00:00">Jan 22, 2015</time></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class=td-block-span12>
                <div class="td_module_6 td_module_wrap td-animation-stack">
                    <div class=td-module-thumb><a
                            href="http://demo.tagdiv.com/newspaper/td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/"
                            rel=bookmark
                            title="Zeta Architecture: Hexagon is the new circle in 2016"><img
                                width=100 height=70 class=entry-thumb
                                src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/01/house-interior-100x70.jpg"
                                alt=""
                                title="Zeta Architecture: Hexagon is the new circle in 2016"/></a></div>
                    <div class=item-details>
                        <h3 class="entry-title td-module-title"><a
                                href="http://demo.tagdiv.com/newspaper/td-post-zeta-architecture-hexagon-is-the-new-circle-in-2016/"
                                rel=bookmark
                                title="Zeta Architecture: Hexagon is the new circle in 2016">Zeta
                                Architecture: Hexagon is the new circle in 2016</a></h3>
                        <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-01-22T05:44:07+00:00">Jan 22, 2015</time></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class=td-block-span12>
                <div class="td_module_6 td_module_wrap td-animation-stack">
                    <div class=td-module-thumb><a
                            href="http://demo.tagdiv.com/newspaper/td-post-what-do-i-need-to-make-it-in-business/"
                            rel=bookmark title="What Do I Need To Make It In Business?"><img
                                width=100 height=70 class=entry-thumb
                                src="http://demo.tagdiv.com/newspaper/wp-content/uploads/2015/04/bag-100x70.jpg"
                                alt="" title="What Do I Need To Make It In Business?"/></a></div>
                    <div class=item-details>
                        <h3 class="entry-title td-module-title"><a
                                href="http://demo.tagdiv.com/newspaper/td-post-what-do-i-need-to-make-it-in-business/"
                                rel=bookmark title="What Do I Need To Make It In Business?">What Do
                                I Need To Make It In Business?</a></h3>
                        <div class=td-module-meta-info>
                                            <span class=td-post-date><time class="entry-date updated td-module-date"
                                                                           datetime="2015-04-21T06:15:43+00:00">Apr 21, 2015</time></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=td-next-prev-wrap><a href="#" class="td-ajax-prev-page ajax-page-disabled"
                                        id=prev-page-td_uid_20_57fec2bd8bd22
                                        data-td_block_id=td_uid_20_57fec2bd8bd22><i
                    class="td-icon-font td-icon-menu-left"></i></a><a href="#" class=td-ajax-next-page
                                                                      id=next-page-td_uid_20_57fec2bd8bd22
                                                                      data-td_block_id=td_uid_20_57fec2bd8bd22><i
                    class="td-icon-font td-icon-menu-right"></i></a></div>
    </div>
</div>