<?php
$arr_hot_content = unserialize(ARR_HOT_CONTENT);
?>
<div id="adrighttop" class="adbox">
    <!-- tintuc_300_600 -->
    <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:600px"
         data-ad-client="ca-pub-5263187211037791"
         data-ad-slot="3121065900"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>

<div class="top-news">
    <div class="title-top-news">Được xem nhiều</div>
    <ul>
        <?php foreach ($arr_hot_content as $content) { ?>
            <li class="item-top">
                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]) ?>">
                    <img src="<?php echo $content['cont_resize_image'] ?>"
                         alt="<?php echo $content['cont_title'] ?>"/>
                    <?php echo $content['cont_title'] ?>
                </a>
            </li>
        <?php } ?>
    </ul>
</div>

<div class="adbox fbbox">
<!--    <ins class="adsbygoogle"-->
<!--         style="display:inline-block;width: 300px;height: 250px"-->
<!--         data-ad-client="ca-pub-5263187211037791"-->
<!--         data-ad-slot="8521797908"></ins>-->
<!--    <script>-->
<!--        (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--    </script>-->
</div>
<div id="adrightsecond" class="adbox">
<!--    <ins class="adsbygoogle"-->
<!--         style="display:inline-block;width: 300px;height: 600px"-->
<!--         data-ad-client="ca-pub-5263187211037791"-->
<!--         data-ad-slot="8521797908"></ins>-->
<!--    <script>-->
<!--        (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--    </script>-->
</div>
